# file_server_clean_up — Safe file audit & cleanup candidates

**What this notebook does**
- Recursively scans a target folder
- Flags obvious junk (OS temp/metadata, zero-byte files, etc.)
- Detects *content duplicates* using hashes (safe, filename-independent)
- Chooses one file to **KEEP** per duplicate set (configurable)
- Exports a **CSV** listing paths and files flagged as **DELETE_CANDIDATE** (no deletion by default)

**Safety**: This notebook does **not** delete anything unless you explicitly enable the optional quarantine step at the end.

## 0) Install checklist (run once)
You should already have created the conda environment and installed dependencies. See the repo README / setup steps from the chat.

In [1]:
import os
import sys
import math
import time
import hashlib
from dataclasses import dataclass
from pathlib import Path
from datetime import datetime

import pandas as pd
from tqdm import tqdm

print('Python:', sys.version)
print('CWD:', os.getcwd())

Python: 3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:05:38) [MSC v.1929 64 bit (AMD64)]
CWD: c:\00_dev\file_server_clean_up\notebooks

## 1) Configuration (edit these)

In [2]:
# === REQUIRED: set the folder you want to scan ===
# Windows example:
# ROOT = Path(r"D:\\FILE_SERVER_EXPORT")
# Network share example:
# ROOT = Path(r"\\\\SERVER\\Share\\SomeFolder")

ROOT = Path(r"Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING")

# Where to write outputs
OUTPUT_DIR = Path("..") / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Exclusions
EXCLUDE_DIR_NAMES = {
    ".git", ".ipynb_checkpoints", "__pycache__", "node_modules",
    "$RECYCLE.BIN", "System Volume Information"
}

# Obvious junk filenames/extensions (add as needed)
JUNK_FILENAMES = {
    ".DS_Store", "Thumbs.db", "desktop.ini", "Icon\r", "._.DS_Store"
}
JUNK_EXTENSIONS = {
    ".tmp", ".temp", ".swp", ".swo", ".bak", ".old", ".dwl", ".dwl2", ".~lock"
}

# Duplicate detection / hashing
HASH_ALGO = "blake2b"   # blake2b is fast & in hashlib
FAST_HASH_BYTES = 2 * 1024 * 1024  # 2 MiB from head + 2 MiB from tail
FULL_HASH_FOR_FINAL_GROUPS = True  # set False to speed up but risk rare collisions

# How to pick the KEEP file within each duplicate group
# Options: "newest_mtime", "oldest_mtime", "shortest_path"
DUP_KEEP_STRATEGY = "newest_mtime"

# Optional directory preferences (higher wins). Example: prefer a 'CURRENT' folder.
# Provide as substrings (case-insensitive) or absolute paths.
PREFERRED_PATH_SUBSTRINGS = [
    # r"\\CURRENT\\",
    # r"\\_LATEST\\",
]

# Minimum file size (bytes) to consider for duplicate grouping
MIN_SIZE_FOR_DUP_CHECK = 1

# CSV name
RUN_TAG = datetime.now().strftime("%Y%m%d_%H%M%S")
CSV_PATH = OUTPUT_DIR / f"cleanup_candidates_{RUN_TAG}.csv"

assert ROOT.exists(), f"ROOT does not exist: {ROOT}"

## 2) File scan (metadata only)

In [3]:
def iter_files(root: Path):
    # Conservative walk: ignore symlinks by default
    for dirpath, dirnames, filenames in os.walk(root):
        # prune excluded directories in-place
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIR_NAMES]
        for fn in filenames:
            p = Path(dirpath) / fn
            try:
                if p.is_symlink():
                    continue
                st = p.stat()
            except (FileNotFoundError, PermissionError, OSError):
                continue
            yield {
                "path": str(p),
                "name": p.name,
                "ext": p.suffix.lower(),
                "size": int(st.st_size),
                "mtime": float(st.st_mtime),
            }

rows = []
for rec in tqdm(iter_files(ROOT), desc="Scanning", unit="files"):
    rows.append(rec)

df = pd.DataFrame(rows)
df["mtime_iso"] = pd.to_datetime(df["mtime"], unit="s", utc=True).dt.tz_convert(None).astype(str)
df["is_zero_bytes"] = df["size"] == 0
df["is_junk_name"] = df["name"].isin(JUNK_FILENAMES)
df["is_junk_ext"] = df["ext"].isin(JUNK_EXTENSIONS)
df["junk_reason"] = ""
df.loc[df["is_zero_bytes"], "junk_reason"] += "zero_bytes;"
df.loc[df["is_junk_name"], "junk_reason"] += "junk_filename;"
df.loc[df["is_junk_ext"], "junk_reason"] += "junk_extension;"

df.shape, df.head()

Scanning: 1015files [03:52,  4.37files/s]

((1015, 10),
                                                 path  \
 0  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 1  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 2  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 3  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 4  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...

                                         name   ext     size         mtime  \
 0  SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg  .dwg   621200  1.667403e+09
 1         01_SONADO_OITYLO_KATOPSH ST A'.pdf  .pdf  1865245  1.650031e+09
 2         02_SONADO_OITYLO_KATOPSH ST B'.pdf  .pdf  4482305  1.650031e+09
 3         03_SONADO_OITYLO_KATOPSH ST C'.pdf  .pdf  5285680  1.650031e+09
 4         04_SONADO_OITYLO_KATOPSH ST D'.pdf  .pdf  4610105  1.650031e+09

                        mtime_iso  is_zero_bytes  is_junk_name  is_junk_ext  \
 0  2022-11-02 15:31:59.000000000          False         False        False
 1  2022-04-15 13:53:09.852024317          False         False        False
 2  2022-04-15 13:53:13.164429188          False         False        False
 3  2022-04-15 13:53:16.055287838          False         False        False
 4  2022-04-15 13:53:21.274787664          False         False        False

   junk_reason
 0
 1
 2
 3
 4              )

## 3) Hashing helpers

In [4]:
def _new_hasher(algo: str):
    if algo == "blake2b":
        return hashlib.blake2b(digest_size=32)
    if algo == "sha256":
        return hashlib.sha256()
    raise ValueError(f"Unsupported algo: {algo}")

def fast_fingerprint(path: str, size: int, algo: str = HASH_ALGO, nbytes: int = FAST_HASH_BYTES) -> str:
    """Fast fingerprint: hash(first nbytes + last nbytes + size)."""
    h = _new_hasher(algo)
    h.update(str(size).encode("utf-8"))
    p = Path(path)
    with p.open("rb") as f:
        head = f.read(nbytes)
        h.update(head)
        if size > nbytes:
            # tail
            try:
                f.seek(max(0, size - nbytes))
                tail = f.read(nbytes)
                h.update(tail)
            except OSError:
                # some special files may not seek cleanly
                pass
    return h.hexdigest()

def full_hash(path: str, algo: str = HASH_ALGO, chunk_size: int = 8 * 1024 * 1024) -> str:
    h = _new_hasher(algo)
    p = Path(path)
    with p.open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()

## 4) Duplicate detection (size → fast hash → full hash)

In [5]:
df["dup_eligible"] = df["size"] >= MIN_SIZE_FOR_DUP_CHECK

# Pass 1: only consider size groups with >1 files
size_counts = df.loc[df["dup_eligible"], "size"].value_counts()
candidate_sizes = set(size_counts[size_counts > 1].index.tolist())

cand = df[df["dup_eligible"] & df["size"].isin(candidate_sizes)].copy()
print("Duplicate candidates by size:", len(cand), "files across", len(candidate_sizes), "sizes")

# Pass 2: compute fast fingerprints for candidates
fast_hashes = []
for path, size in tqdm(zip(cand["path"], cand["size"]), total=len(cand), desc="Fast hashing"):
    try:
        fast_hashes.append(fast_fingerprint(path, int(size)))
    except (FileNotFoundError, PermissionError, OSError):
        fast_hashes.append(None)

cand["hash_fast"] = fast_hashes
cand = cand.dropna(subset=["hash_fast"]).copy()

# Pass 3: group by (size, hash_fast), and optionally full-hash within groups >1
cand["group_fast"] = cand.groupby(["size", "hash_fast"]).ngroup()
fast_group_sizes = cand["group_fast"].value_counts()
fast_dupe_groups = fast_group_sizes[fast_group_sizes > 1].index.tolist()

cand["hash_full"] = None
if FULL_HASH_FOR_FINAL_GROUPS and fast_dupe_groups:
    mask = cand["group_fast"].isin(fast_dupe_groups)
    sub = cand.loc[mask].copy()
    fulls = []
    for path in tqdm(sub["path"], total=len(sub), desc="Full hashing"):
        try:
            fulls.append(full_hash(path))
        except (FileNotFoundError, PermissionError, OSError):
            fulls.append(None)
    cand.loc[mask, "hash_full"] = fulls

# Determine the final duplicate key
cand["dup_key"] = cand.apply(
    lambda r: (r["size"], r["hash_full"]) if (FULL_HASH_FOR_FINAL_GROUPS and pd.notna(r["hash_full"])) else (r["size"], r["hash_fast"]),
    axis=1,
)

cand["dup_group_id"] = cand.groupby("dup_key").ngroup()
dup_group_counts = cand["dup_group_id"].value_counts()
dup_groups = dup_group_counts[dup_group_counts > 1].index.tolist()

print("Final duplicate groups:", len(dup_groups))
dup_group_counts.head(10)

Duplicate candidates by size: 842 files across 340 sizes

Fast hashing: 100%|██████████| 842/842 [05:52<00:00,  2.39it/s]
Full hashing: 100%|██████████| 830/830 [06:56<00:00,  1.99it/s]

Final duplicate groups: 339

dup_group_id
100    4
103    4
332    4
333    4
347    4
346    4
337    4
338    4
176    4
340    4
Name: count, dtype: int64

## 5) Decide KEEP vs DELETE_CANDIDATE

In [6]:
def preference_score(path: str) -> int:
    p = path.lower()
    score = 0
    for i, sub in enumerate(PREFERRED_PATH_SUBSTRINGS):
        if sub and sub.lower() in p:
            # earlier in list = higher weight
            score += (len(PREFERRED_PATH_SUBSTRINGS) - i) * 10_000
    # shorter path gets a tiny bump (helps tie-break)
    score += max(0, 500 - len(path))
    return score

cand["pref_score"] = cand["path"].apply(preference_score)

def pick_keeper(group: pd.DataFrame) -> int:
    if DUP_KEEP_STRATEGY == "newest_mtime":
        # preference score dominates, then newest mtime
        g = group.sort_values(["pref_score", "mtime"], ascending=[False, False])
    elif DUP_KEEP_STRATEGY == "oldest_mtime":
        g = group.sort_values(["pref_score", "mtime"], ascending=[False, True])
    elif DUP_KEEP_STRATEGY == "shortest_path":
        g = group.assign(path_len=group["path"].str.len()).sort_values(["pref_score", "path_len"], ascending=[False, True])
    else:
        raise ValueError(f"Unknown strategy: {DUP_KEEP_STRATEGY}")
    return g.index[0]

# Mark keepers within each duplicate group
cand["dup_is_keeper"] = False
keepers = []
for gid, g in tqdm(cand[cand["dup_group_id"].isin(dup_groups)].groupby("dup_group_id"), desc="Choosing keepers"):
    keep_idx = pick_keeper(g)
    keepers.append(keep_idx)
cand.loc[keepers, "dup_is_keeper"] = True

# Merge duplicate info back to full df
df = df.merge(
    cand[["path", "hash_fast", "hash_full", "dup_group_id", "dup_is_keeper"]],
    on="path", how="left"
)

# Decision logic (conservative):
# - If junk => DELETE_CANDIDATE
# - Else if in duplicate group and not keeper => DELETE_CANDIDATE
# - Else => KEEP
df["decision"] = "KEEP"
df["reason"] = "";
df.loc[df["junk_reason"] != "", "decision"] = "DELETE_CANDIDATE"
df.loc[df["junk_reason"] != "", "reason"] += df.loc[df["junk_reason"] != "", "junk_reason"]

dup_nonkeepers = df["dup_group_id"].notna() & (df["dup_is_keeper"] == False)
df.loc[dup_nonkeepers & (df["decision"] == "KEEP"), "decision"] = "DELETE_CANDIDATE"
df.loc[dup_nonkeepers & (df["decision"] == "DELETE_CANDIDATE"), "reason"] += "duplicate_nonkeeper;"
df.loc[dup_nonkeepers & (df["decision"] == "KEEP"), "reason"] += "duplicate_nonkeeper;"

# For keepers in a dupe group, note it
df.loc[df["dup_group_id"].notna() & (df["dup_is_keeper"] == True), "reason"] += "duplicate_keeper;"

# Clean reason formatting
df["reason"] = df["reason"].str.strip(";")

df["decision"].value_counts(), df.head()

Choosing keepers: 100%|██████████| 339/339 [00:00<00:00, 3324.35it/s]

(decision
 DELETE_CANDIDATE    527
 KEEP                488
 Name: count, dtype: int64,
                                                 path  \
 0  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 1  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 2  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 3  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...
 4  Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...

                                         name   ext     size         mtime  \
 0  SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg  .dwg   621200  1.667403e+09
 1         01_SONADO_OITYLO_KATOPSH ST A'.pdf  .pdf  1865245  1.650031e+09
 2         02_SONADO_OITYLO_KATOPSH ST B'.pdf  .pdf  4482305  1.650031e+09
 3         03_SONADO_OITYLO_KATOPSH ST C'.pdf  .pdf  5285680  1.650031e+09
 4         04_SONADO_OITYLO_KATOPSH ST D'.pdf  .pdf  4610105  1.650031e+09

                        mtime_iso  is_zero_bytes  is_junk_name  is_junk_ext  \
 0  2022-11-02 15:31:59.000000000          False         False        False
 1  2022-04-15 13:53:09.852024317          False         False        False
 2  2022-04-15 13:53:13.164429188          False         False        False
 3  2022-04-15 13:53:16.055287838          False         False        False
 4  2022-04-15 13:53:21.274787664          False         False        False

   junk_reason  dup_eligible  \
 0                      True
 1                      True
 2                      True
 3                      True
 4                      True

                                            hash_fast  \
 0  3bf3f90138bb3092682a349e45a1abc48e7c09d7af33c8...
 1  f4e75ed25e4179a341eb205d9137733bf50020fa762845...
 2  83e5bf3b8608bef575ba68779d9a3a0084e2c68dcccf50...
 3  be30100a2a38767a07364ffe8c80a8dbd83686a0ba0892...
 4  c9227b4e1ee3769658f7ea8a6e824a37e10913e13f55cc...

                                            hash_full  dup_group_id  \
 0  d36eb37a57777e47a2e52f94cbfcea6dc85b1212c6ca06...          94.0
 1  edc4f934a6994a217fadb92688bc37ea7eac39819a1db8...         172.0
 2  99745a284cf7c7ce5eeb6623b23239f1bd5457bb196a1c...         264.0
 3  56e491fb5a1621cfd62f75c45feb491384bddb621df3e0...         273.0
 4  ae2840f40f639859b67617d4e96909d115d3b89335fd29...         265.0

   dup_is_keeper decision            reason
 0          True     KEEP  duplicate_keeper
 1          True     KEEP  duplicate_keeper
 2          True     KEEP  duplicate_keeper
 3          True     KEEP  duplicate_keeper
 4          True     KEEP  duplicate_keeper  )

## 6) Export CSV (paths + flags)

In [7]:
out = df[[
    "path", "decision", "reason", "size", "mtime_iso",
    "ext", "hash_fast", "hash_full", "dup_group_id", "dup_is_keeper"
]].copy()

out.to_csv(CSV_PATH, index=False, encoding="utf-8")
print("Wrote:", CSV_PATH)
out["decision"].value_counts()

Wrote: ..\outputs\cleanup_candidates_20260302_141826.csv

decision
DELETE_CANDIDATE    527
KEEP                488
Name: count, dtype: int64

## 7) Review helpers

In [8]:
# Preview what would be deleted
out[out["decision"] == "DELETE_CANDIDATE"].head(50)

,path,decision,reason,size,mtime_iso,ext,hash_fast,hash_full,dup_group_id,dup_is_keeper
35,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_filename,201728,2026-03-02 06:15:04.759999990,.db,NaN,NaN,NaN,NaN
36,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,664636,2022-11-02 15:31:59.000000000,.bak,055c707cbb87860279fe4c5d0c54e25f469745f4667040...,68e798b735d59dc43921dfd2f747dee588f7c8089ba6e8...,100.0,False
37,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,692091,2022-11-02 15:31:59.000000000,.dwg,e807257c06127f08c623938fb92bd9912d64e8aea54406...,98680a7abb133af8e4a5982793a7fd3d755f8ddab3b38a...,103.0,False
38,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,False
39,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,9598848,2022-11-02 15:31:59.000000000,.dwg,038f8df44a1ab0393616d561ebba2d31887edd94d2a899...,26ea00678608e44154dc5aa8808566c719c4837a6bd1d7...,333.0,False
40,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,False
41,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,25864399,2022-11-02 15:31:59.000000000,.dwg,39f3f0e383d75266718cc953ea381f7f3549366440f084...,6ad4e54ec9e9255e0831849cebf97260796907108cbde3...,346.0,False
42,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,False
43,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,14532198,2022-11-02 15:31:59.000000000,.dwg,22f771bf30cd1ced37a60ee949b7a4c52953f822d9ad7e...,292b5fd7480f9e9734b035eaec274b6b4daa2a0cd5706d...,338.0,False
47,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,664636,2022-11-02 15:31:59.000000000,.bak,055c707cbb87860279fe4c5d0c54e25f469745f4667040...,68e798b735d59dc43921dfd2f747dee588f7c8089ba6e8...,100.0,True
49,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,True
51,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,True
53,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,True
55,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,28062159,2022-11-02 15:31:59.000000000,.bak,0c9c733d7b975278214c02ab89567faca1f5960e1f46f4...,5b3727d7e1f6b61acacf45d44f5fee7cb246d4538add23...,350.0,True
57,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,6390571,2022-11-02 15:31:59.000000000,.bak,82f2a0969555af6d6b98005f525b8dec0fdbbf84195415...,b1bf0c33acf0bb9e81bf3174680e9c3d09ae53c94539f0...,292.0,True
59,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,5779546,2022-11-02 15:31:59.000000000,.bak,88a79ad2e1bfef8fb431f78f2dbbda396f0f06693728dd...,92a4699c0e7afd5076967a83d441cf51bc09f69085341b...,280.0,True
71,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_filename;duplicate_nonkeeper,6148,2025-11-07 11:24:58.865989447,,6a5ed1810dce53deb5755602098e996f1c54e6c18548f0...,None,6.0,False
197,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_filename,69120,2023-02-13 12:21:16.013223886,.db,NaN,NaN,NaN,NaN
203,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension,51,2023-03-01 14:05:28.639566660,.dwl,NaN,NaN,NaN,NaN
204,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension,217,2023-03-01 14:05:28.920873404,.dwl2,NaN,NaN,NaN,NaN
208,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_filename,6144,2023-02-13 12:22:05.263608456,.db,NaN,NaN,NaN,NaN
215,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,319181,2023-02-13 12:23:06.701673031,.pdf,18cdf1e7b6a4f88c3021069062ab3c3cd3417c2ef7ca26...,e906945401628425afdb7b2a58df710ec28ef8b1865090...,50.0,False
216,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,567971,2023-02-13 12:23:12.936168194,.pdf,f609ab18540f86ded42091ae982ab6ca4d948afd2fa869...,97457f2437d3f702307211656efc71ebaec1b47415255b...,89.0,False
217,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,903555,2023-02-13 12:23:19.326842785,.pdf,9d4eccc9f13d53d09ef234f2e1ef478456862855c93b1d...,f7f91d9994658beb56413a83e207f2d7879465bf5f3833...,117.0,False
218,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,2931501,2023-02-13 12:23:26.514355421,.pdf,97b5798c715e5acc665deb63ecea1db5114d59120b24aa...,3f69d2bc877362179829f4f98c5c71cbef259ac577a7a2...,215.0,False
219,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3557706,2023-02-13 12:23:33.967601776,.pdf,27a1a7ce1f9d14d6f5dd824278dc9c187c621c8731f6d9...,5d8742a693e707a293442352e670ab68eb0421c1021230...,236.0,False
220,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3829093,2023-02-13 12:23:41.373914719,.pdf,656c0c3526ad5e1a1392826e6aa4fa8701c4cbcf877266...,504f5c70aa2bbb18f0129edac3f2f76ab7b8863fc232cf...,247.0,False
221,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3947968,2023-02-13 12:23:49.030234098,.pdf,8ae4c9b3ce405102050411afb2e7da73704ed0f3ed9dd4...,e2e2a73fef577f2d07a64a21162de7e72453ae6f848bad...,254.0,False
222,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,406135,2023-02-13 12:23:55.092790127,.pdf,a56c785f858b8f324e6f4df6b8c6ef1ea607b82a2ee032...,13c59e9f8160e76d3aad557e2482447af3efe4815b6302...,68.0,False
223,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,269078,2023-02-13 12:24:00.889713049,.pdf,4465efe7a52f4deda5ae4ce2d05a860a08299971904780...,7ec2790723f5ba65f7c3a7c47804cbcdf7d6e1d5b66e1c...,42.0,False
224,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,583845,2023-02-13 12:24:07.311606646,.pdf,e6b4d49c5d7f0077af37e346a7e9f48909f13cef0f47e1...,15f6869f52e3d9563bae39f7b8c22108118a25bd9e2432...,92.0,False
225,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,2387024,2023-02-13 12:24:14.592914820,.pdf,6d15cae8d7ac6ebb9e171e016952cfc84f41f20670921a...,268b7c3a09bb71afc835a199684de61c113b287981dac0...,193.0,False
226,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3301194,2023-02-13 12:24:21.733756781,.pdf,abeb56c57b1edc9028f78a57ff07bbf00243f704e2bcc4...,d8b423bcc2eb70c552fd17254e53a11177e4d120b463cd...,227.0,False
227,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3715767,2023-02-13 12:24:29.046172619,.pdf,ccd7ea9629237016e93b4f1034d6b36c1e48cbe7b1602a...,d00f4f057d7d535174fac0bdbd486a8ac05c643c40e94a...,240.0,False
228,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3862183,2023-02-13 12:24:36.561860561,.pdf,f186c1ffa9a9cd4e4c3c0d65708589d8b508ee0854de37...,e8a40bc4ac5285951b6db1b93c8a569315d4c19a936640...,249.0,False
229,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,784113,2023-02-13 12:24:42.952598333,.pdf,7d23afd3ad435db5c0ed8c477043e233656678e0a8f761...,5d926031cd9f504dfcfa1b175f68f39c0cc390b0c7f384...,108.0,False
230,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,574186,2023-02-13 12:24:49.249531031,.pdf,d2aa2d904b9b3c602ffc7afdff07bf90e17ed4770bf7ed...,8de6c631b0324f4ce001dab975d1d5dafb1c39f8d789f7...,91.0,False
231,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,406654,2023-02-13 12:24:55.218332052,.pdf,f7fd5d9da503ecc636a2f46188b154fb93c6acf4c4f31c...,46727e02072912f410f800acac0dd52b4eb9dcbd3b34b2...,69.0,False
232,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,1634851,2023-02-13 12:25:02.655896664,.pdf,d562432baa547cb59c7586b517d9f6c0e8e84d0a718287...,8150c901ace37c84efe09f76e13392a883200df3f496a2...,153.0,False
233,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,495260,2023-02-13 12:25:09.359022379,.pdf,f4fc4cfa2854d791928fd0797d94eb59f63ff8a6c80ec3...,385e8b2439de052e84c41847163852e9051258b776b497...,86.0,False
234,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,453271,2023-02-13 12:25:15.405967951,.pdf,1a2b26ed521b7edc62917c7d92579e8b90054ba94a2b1f...,110e14c4356cf193b4794465fbe20e3feb3b5144eed001...,73.0,False
235,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,493419,2023-02-13 12:25:21.546687603,.pdf,b028c942a245da076971fd9856f2f65eb88a8363c9570c...,ad087d2401b28ee2a8c7e1f924cf06d6a3e76cdd841fee...,82.0,False
236,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,493680,2023-02-13 12:25:27.906127214,.pdf,d7fd4cca566d946860767bd085718f90b47d3ae7a29779...,b7df854a1508b8cf90a9dfc46701cd6694c741cdede643...,83.0,False
237,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,463203,2023-02-13 12:25:34.187434435,.pdf,4c15e3cba8c23d4e50c134ae422a971896e043e5285528...,df210f273fb4b41e8796e7b1b8a0aeb92cebae4d706063...,75.0,False
238,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,573796,2023-02-13 12:25:40.281256676,.pdf,0548183b90ffd72c6762aa3d2eb4134c5a738bd7ab9388...,2b148d70f44e72e715857b896be97aa41ef5bbb2ce8e74...,90.0,False
239,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,2376188,2023-02-13 12:25:47.249995708,.pdf,9d6353452451850456001488a7986113a2a45c53a1086e...,777e633edbc7716bfe313c227a3af7d902e8ba9e83b16e...,192.0,False
240,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3268154,2023-02-13 12:25:54.656377792,.pdf,160dfc5a7247d74603e2341cac5ae265eb9abb6928f30a...,c43c88f737ef9a938fd272238bab77386890821b8762e1...,225.0,False
241,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3703225,2023-02-13 12:26:02.484550238,.pdf,87b121831215c26789e02ac5a2e769d5d39d2efabda35f...,0c3e69284834b88c8a977a1851fd2d2fe5a97e9c3db023...,239.0,False
242,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,1089119,2023-02-13 12:26:09.078370094,.pdf,cc7ceca9c3f3fcd914e3f280648dd539cec5af5471c1f4...,ae2a108fc9e5e8da8cd0ab605d6754fdb3a779370bb162...,129.0,False
243,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,3003991,2023-02-13 12:26:16.094067812,.pdf,4a0b2ff32a0a8e33a424d15efe7281e36f58431f6f709c...,6933640927fab748a9519efca8dc2d4222d27c4bd0fb50...,216.0,False

In [9]:
# Counts by reason (for DELETE_CANDIDATE rows)
tmp = out[out['decision'] == 'DELETE_CANDIDATE'].copy()
tmp['reason_list'] = tmp['reason'].fillna('').apply(lambda s: [r for r in s.split(';') if r])
reason_counts = (
    tmp.explode('reason_list')
       .query("reason_list != ''")
       .groupby('reason_list')
       .size()
       .sort_values(ascending=False)
)
reason_counts.head(50)

reason_list
duplicate_nonkeeper    503
junk_extension          39
junk_filename           20
duplicate_keeper        11
dtype: int64

In [10]:
# Largest delete candidates (often duplicates)
out[out["decision"] == "DELETE_CANDIDATE"].sort_values("size", ascending=False).head(50)

,path,decision,reason,size,mtime_iso,ext,hash_fast,hash_full,dup_group_id,dup_is_keeper
974,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,28062159,2022-11-02 15:31:59.000000000,.bak,0c9c733d7b975278214c02ab89567faca1f5960e1f46f4...,5b3727d7e1f6b61acacf45d44f5fee7cb246d4538add23...,350.0,False
55,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,28062159,2022-11-02 15:31:59.000000000,.bak,0c9c733d7b975278214c02ab89567faca1f5960e1f46f4...,5b3727d7e1f6b61acacf45d44f5fee7cb246d4538add23...,350.0,True
650,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,28062159,2022-11-02 15:31:59.000000000,.bak,0c9c733d7b975278214c02ab89567faca1f5960e1f46f4...,5b3727d7e1f6b61acacf45d44f5fee7cb246d4538add23...,350.0,False
975,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,27783962,2022-11-02 15:31:59.000000000,.dwg,896982e43dd1ec115dac5669a29362d5c5f8721c97af75...,d98a7ac2f56dabc05853f4f124949754d88626f3a11547...,349.0,False
651,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,27783962,2022-11-02 15:31:59.000000000,.dwg,896982e43dd1ec115dac5669a29362d5c5f8721c97af75...,d98a7ac2f56dabc05853f4f124949754d88626f3a11547...,349.0,False
680,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,27562520,2022-11-02 15:31:59.000000000,.pdf,2b7d6ab5499c268b2bc64b1d150241132091dce3098032...,bb898e194bb2a0b83ddf8d7ad6bbffc4eb0f2e559f0894...,348.0,False
1005,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,27562520,2022-11-02 15:31:59.000000000,.pdf,2b7d6ab5499c268b2bc64b1d150241132091dce3098032...,bb898e194bb2a0b83ddf8d7ad6bbffc4eb0f2e559f0894...,348.0,False
646,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,False
40,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,False
51,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,True
970,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,26347123,2022-11-02 15:31:59.000000000,.bak,4bd5483f21da657324d6e1bc37eae60ca8317525786854...,e4403d8df4dc956d35e48fe244ee0e9f9d0b1faec6b80e...,347.0,False
971,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,25864399,2022-11-02 15:31:59.000000000,.dwg,39f3f0e383d75266718cc953ea381f7f3549366440f084...,6ad4e54ec9e9255e0831849cebf97260796907108cbde3...,346.0,False
647,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,25864399,2022-11-02 15:31:59.000000000,.dwg,39f3f0e383d75266718cc953ea381f7f3549366440f084...,6ad4e54ec9e9255e0831849cebf97260796907108cbde3...,346.0,False
41,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,25864399,2022-11-02 15:31:59.000000000,.dwg,39f3f0e383d75266718cc953ea381f7f3549366440f084...,6ad4e54ec9e9255e0831849cebf97260796907108cbde3...,346.0,False
1009,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,23953024,2022-11-02 15:31:59.000000000,.pdf,60b429c1b4505c5ae6a772112cfc84ee6f43b3fa0395fe...,dab6ff019f731a314bc2a8605ed71663ad01a15623c6b3...,345.0,False
684,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,23953024,2022-11-02 15:31:59.000000000,.pdf,60b429c1b4505c5ae6a772112cfc84ee6f43b3fa0395fe...,dab6ff019f731a314bc2a8605ed71663ad01a15623c6b3...,345.0,False
889,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20888705,2025-10-17 14:06:30.000000000,.pdf,5f43e9deea0bd3d507a6ec0b2d66989d487dba3058eb73...,5ead157b15df5fb3205127bde0dfd50681e42ae69a894a...,344.0,False
419,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20888705,2025-05-13 09:10:07.900696993,.pdf,5f43e9deea0bd3d507a6ec0b2d66989d487dba3058eb73...,5ead157b15df5fb3205127bde0dfd50681e42ae69a894a...,344.0,False
387,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20888705,2025-10-17 14:06:30.000000000,.pdf,5f43e9deea0bd3d507a6ec0b2d66989d487dba3058eb73...,5ead157b15df5fb3205127bde0dfd50681e42ae69a894a...,344.0,False
685,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20359415,2022-11-02 15:31:59.000000000,.pdf,ec76f73c9cfbb5fcd6c7636214c407ef3c0c7a2db40d56...,7ea321a51783d0df066e18baf10e7f6c8597b6943d0109...,343.0,False
1010,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20359415,2022-11-02 15:31:59.000000000,.pdf,ec76f73c9cfbb5fcd6c7636214c407ef3c0c7a2db40d56...,7ea321a51783d0df066e18baf10e7f6c8597b6943d0109...,343.0,False
429,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,20023823,2025-10-02 08:52:42.694098949,.dwg,ab737c645f286c43b963f76dbe52a716463f6f89d6d317...,02e8452e52b36aec261c23ebf375d5cfa59ac84fa2f6e8...,342.0,False
1008,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,18651305,2022-11-02 15:31:59.000000000,.pdf,f0b593216a0ba5d9dad9ad609870d520c465ad8b8b92ff...,fff1e1323e2a246c5037e55742675fa71605fdc5f9c60d...,341.0,False
683,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,18651305,2022-11-02 15:31:59.000000000,.pdf,f0b593216a0ba5d9dad9ad609870d520c465ad8b8b92ff...,fff1e1323e2a246c5037e55742675fa71605fdc5f9c60d...,341.0,False
888,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,18073252,2025-10-17 14:06:30.000000000,.pdf,9b96956e087e779023f4b293db7ce9cd11dd3b759cbcb7...,0fcaed489858228b0dcbaf28782b637509587d860bd1c3...,340.0,False
430,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,18073252,2025-09-26 07:13:57.645121336,.pdf,9b96956e087e779023f4b293db7ce9cd11dd3b759cbcb7...,0fcaed489858228b0dcbaf28782b637509587d860bd1c3...,340.0,False
386,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,18073252,2025-10-17 14:06:30.000000000,.pdf,9b96956e087e779023f4b293db7ce9cd11dd3b759cbcb7...,0fcaed489858228b0dcbaf28782b637509587d860bd1c3...,340.0,False
682,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,17821291,2022-11-02 15:31:59.000000000,.pdf,cf0fbb7b476e0a1b1ba3bb48af01f69fa1bcab13e4f725...,4cc2d4e2cf9012147329c842aa0b169215451aa8369005...,339.0,False
1007,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,17821291,2022-11-02 15:31:59.000000000,.pdf,cf0fbb7b476e0a1b1ba3bb48af01f69fa1bcab13e4f725...,4cc2d4e2cf9012147329c842aa0b169215451aa8369005...,339.0,False
43,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,14532198,2022-11-02 15:31:59.000000000,.dwg,22f771bf30cd1ced37a60ee949b7a4c52953f822d9ad7e...,292b5fd7480f9e9734b035eaec274b6b4daa2a0cd5706d...,338.0,False
649,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,14532198,2022-11-02 15:31:59.000000000,.dwg,22f771bf30cd1ced37a60ee949b7a4c52953f822d9ad7e...,292b5fd7480f9e9734b035eaec274b6b4daa2a0cd5706d...,338.0,False
973,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,14532198,2022-11-02 15:31:59.000000000,.dwg,22f771bf30cd1ced37a60ee949b7a4c52953f822d9ad7e...,292b5fd7480f9e9734b035eaec274b6b4daa2a0cd5706d...,338.0,False
42,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,False
53,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,True
972,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,False
648,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,14532003,2022-11-02 15:31:59.000000000,.bak,6cbf074e5d49b8b24b1c6201390416d929bcfe5ed02596...,f6689a35b8ddf1cb3c55d13adcfab6394b1f5ea57786b5...,337.0,False
388,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,12727455,2025-10-17 14:06:30.000000000,.pdf,9674ffd33bd100c90063d7b4779eb9b129723b803ee51a...,b002da0ef44338fcd278ffc46eb59fd26fc4000d892c6b...,336.0,False
424,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,12727455,2025-06-04 06:10:40.585362911,.pdf,9674ffd33bd100c90063d7b4779eb9b129723b803ee51a...,b002da0ef44338fcd278ffc46eb59fd26fc4000d892c6b...,336.0,False
890,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,12727455,2025-10-17 14:06:30.000000000,.pdf,9674ffd33bd100c90063d7b4779eb9b129723b803ee51a...,b002da0ef44338fcd278ffc46eb59fd26fc4000d892c6b...,336.0,False
421,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,12089675,2025-04-10 06:06:48.017771244,.dwg,9bbd0264408d412b1b26e172706a864866db76f3611ae4...,61eeb9cb2de5b3a263a0f1398a0df04d412cf652cf174a...,335.0,False
426,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,11356331,2025-06-20 10:32:15.877753735,.pdf,68e0e1ef831e748358f2eada582d1964d14f7a9099ac37...,8e669a34e296192c3cf884226cc7c4b89ce9bb1f74e550...,334.0,False
416,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,11356331,2025-10-17 09:22:33.916575193,.pdf,68e0e1ef831e748358f2eada582d1964d14f7a9099ac37...,8e669a34e296192c3cf884226cc7c4b89ce9bb1f74e550...,334.0,False
645,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,9598848,2022-11-02 15:31:59.000000000,.dwg,038f8df44a1ab0393616d561ebba2d31887edd94d2a899...,26ea00678608e44154dc5aa8808566c719c4837a6bd1d7...,333.0,False
969,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,9598848,2022-11-02 15:31:59.000000000,.dwg,038f8df44a1ab0393616d561ebba2d31887edd94d2a899...,26ea00678608e44154dc5aa8808566c719c4837a6bd1d7...,333.0,False
39,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,9598848,2022-11-02 15:31:59.000000000,.dwg,038f8df44a1ab0393616d561ebba2d31887edd94d2a899...,26ea00678608e44154dc5aa8808566c719c4837a6bd1d7...,333.0,False
49,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_keeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,True
644,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,False
38,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,False
968,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,junk_extension;duplicate_nonkeeper,9554920,2022-11-02 15:31:59.000000000,.bak,fa7831c4357200d18b7a05593acf8267f6dd61e09aec30...,c5f40c6bcf021969264cd1a41f9649d621196426e3fd76...,332.0,False
423,Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_...,DELETE_CANDIDATE,duplicate_nonkeeper,9366998,2025-05-28 12:59:14.844994307,.pdf,d762445eda4a9410adcef138fa280903e45f941d9a718f...,bf7d24dd2ce1def3a416e7ba2e4d267ea7fd06e5744241...,331.0,False

## 8) OPTIONAL: Quarantine move (safer than delete)
**Default is disabled.** If you enable it, files are moved to a quarantine folder preserving relative paths.

⚠️ Only do this after reviewing the CSV.

In [ ]:
ENABLE_QUARANTINE = True
QUARANTINE_DIR = Path("..") / "quarantine" / f"run_{RUN_TAG}"

def move_to_quarantine(src_path: str, root: Path, quarantine_root: Path):
    src = Path(src_path)
    rel = src.relative_to(root)
    dst = quarantine_root / rel
    dst.parent.mkdir(parents=True, exist_ok=True)

    if dst.exists():
        raise FileExistsError(f"Destination already exists: {dst}")

    try:
        src.replace(dst)  # atomic move on same volume
    except OSError:
        # Cross-volume fallback (e.g., Z: -> C:)
        import shutil
        shutil.move(str(src), str(dst))

if ENABLE_QUARANTINE:
    QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)
    to_move = out[out["decision"] == "DELETE_CANDIDATE"]["path"].tolist()
    moved = 0
    for p in tqdm(to_move, desc="Quarantining"):
        try:
            move_to_quarantine(p, ROOT, QUARANTINE_DIR)
            moved += 1
        except Exception as e:
            print("FAILED:", p, "->", e)
    print(f"Moved {moved}/{len(to_move)} files to {QUARANTINE_DIR}")
else:
    print("Quarantine is disabled (ENABLE_QUARANTINE=False).")

Quarantining:   0%|          | 2/527 [00:00<00:53,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\Thumbs.db'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak'

Quarantining:   1%|          | 4/527 [00:00<00:54,  9.61it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak'

Quarantining:   1%|          | 6/527 [00:00<00:53,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg'

Quarantining:   2%|▏         | 9/527 [00:00<00:53,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg'

Quarantining:   2%|▏         | 11/527 [00:01<00:52,  9.75it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak'

Quarantining:   2%|▏         | 13/527 [00:01<00:52,  9.76it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak'

Quarantining:   3%|▎         | 16/527 [00:01<00:52,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak' -> '..\\quarantine\\run_20260302_141826\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak'

Quarantining:   4%|▎         | 19/527 [00:01<00:52,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\DWGS\KENAK\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\KENAK\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\KENAK\\Thumbs.db'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\DWGS\YDREYSH\21011_YDREYSH_PLANS.dwl -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\YDREYSH\\21011_YDREYSH_PLANS.dwl' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\YDREYSH\\21011_YDREYSH_PLANS.dwl'

Quarantining:   4%|▍         | 21/527 [00:02<00:52,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\DWGS\YDREYSH\21011_YDREYSH_PLANS.dwl2 -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\YDREYSH\\21011_YDREYSH_PLANS.dwl2' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\YDREYSH\\21011_YDREYSH_PLANS.dwl2'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\DWGS\_XREF\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\_XREF\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\DWGS\\_XREF\\Thumbs.db'

Quarantining:   5%|▍         | 24/527 [00:02<00:51,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ANELKYSTHRAS\AN-01_ANELKYSTHRAS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ANELKYSTHRAS\\AN-01_ANELKYSTHRAS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ANELKYSTHRAS\\AN-01_ANELKYSTHRAS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ANELKYSTHRAS\TEYXOS HM MELETHS ANELKYSTHRA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ANELKYSTHRAS\\TEYXOS HM MELETHS ANELKYSTHRA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ANELKYSTHRAS\\TEYXOS HM MELETHS ANELKYSTHRA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-01_APOXETEYSH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-01_APOXETEYSH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-01_APOXETEYSH_PLANS-LEVEL A.pdf'

Quarantining:   5%|▍         | 26/527 [00:02<00:51,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-02_APOXETEYSH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-02_APOXETEYSH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-02_APOXETEYSH_PLANS-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-03_APOXETEYSH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-03_APOXETEYSH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-03_APOXETEYSH_PLANS-LEVEL C.pdf'

Quarantining:   5%|▌         | 28/527 [00:02<00:52,  9.45it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-04_APOXETEYSH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-04_APOXETEYSH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-04_APOXETEYSH_PLANS-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-05_APOXETEYSH_PLANS-DOMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-05_APOXETEYSH_PLANS-DOMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-05_APOXETEYSH_PLANS-DOMA.pdf'

Quarantining:   6%|▌         | 31/527 [00:03<00:51,  9.56it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\AP-06_APOXETEYSH_DIAGR.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-06_APOXETEYSH_DIAGR.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\AP-06_APOXETEYSH_DIAGR.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\APOXETEYSH\HM MELETH APOXETEYSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\HM MELETH APOXETEYSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\APOXETEYSH\\HM MELETH APOXETEYSHS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\ASTH-01_ASTHENH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-01_ASTHENH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-01_ASTHENH_PLANS-LEVEL A.pdf'

Quarantining:   6%|▋         | 34/527 [00:03<00:51,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\ASTH-02_ASTHENH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-02_ASTHENH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-02_ASTHENH_PLANS-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\ASTH-03_ASTHENH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-03_ASTHENH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-03_ASTHENH_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\ASTH-04_ASTHENH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-04_ASTHENH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-04_ASTHENH_PLANS-LEVEL D.pdf'

Quarantining:   7%|▋         | 36/527 [00:03<00:50,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\ASTH-05_ASTHENH_PLANS-DOMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-05_ASTHENH_PLANS-DOMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\ASTH-05_ASTHENH_PLANS-DOMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ASTHENH\TEXNIKH PERIGRAFH ASTHENWN REYMATWN-R-TV.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\TEXNIKH PERIGRAFH ASTHENWN REYMATWN-R-TV.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ASTHENH\\TEXNIKH PERIGRAFH ASTHENWN REYMATWN-R-TV.pdf'

Quarantining:   7%|▋         | 38/527 [00:03<00:50,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\BIOLOGIKOS\MB-01_BIOLOGIKOS_PLANS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\MB-01_BIOLOGIKOS_PLANS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\MB-01_BIOLOGIKOS_PLANS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\BIOLOGIKOS\MB-02_BIOLOGIKOS_DIAGRAM.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\MB-02_BIOLOGIKOS_DIAGRAM.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\MB-02_BIOLOGIKOS_DIAGRAM.pdf'

Quarantining:   8%|▊         | 40/527 [00:04<00:50,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\BIOLOGIKOS\TEYXOS HM MELETHS BIOLOGIKOY.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\TEYXOS HM MELETHS BIOLOGIKOY.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\BIOLOGIKOS\\TEYXOS HM MELETHS BIOLOGIKOY.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf'

Quarantining:   8%|▊         | 43/527 [00:04<00:49,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf'

Quarantining:   9%|▊         | 45/527 [00:04<00:49,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PARARTHMA 2 YPOLOGISMOI.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PARARTHMA 2 YPOLOGISMOI.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PARARTHMA 2 YPOLOGISMOI.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRB-01_PYROSBESH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-01_PYROSBESH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-01_PYROSBESH_PLANS-LEVEL A.pdf'

Quarantining:   9%|▉         | 48/527 [00:04<00:49,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRB-02_PYROSBESH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-02_PYROSBESH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-02_PYROSBESH_PLANS-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRB-03_PYROSBESH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-03_PYROSBESH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-03_PYROSBESH_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRB-04_PYROSBESH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-04_PYROSBESH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRB-04_PYROSBESH_PLANS-LEVEL D.pdf'

Quarantining:   9%|▉         | 50/527 [00:05<00:49,  9.57it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRX-01_PYRANIXNEYSH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-01_PYRANIXNEYSH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-01_PYRANIXNEYSH_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRX-02_PYRANIXNEYSH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-02_PYRANIXNEYSH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-02_PYRANIXNEYSH_PLANS-LEVEL B.pdf'

Quarantining:  10%|▉         | 52/527 [00:05<00:49,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRX-03_PYRANIXNEYSH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-03_PYRANIXNEYSH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-03_PYRANIXNEYSH_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\PRX-04_PYRANIXNEYSH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-04_PYRANIXNEYSH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\PRX-04_PYRANIXNEYSH_PLANS-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\ENERGHTIKH PYR\TEXNIKH PERIGRAFH MON.SYSTHMATON.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\TEXNIKH PERIGRAFH MON.SYSTHMATON.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\ENERGHTIKH PYR\\TEXNIKH PERIGRAFH MON.SYSTHMATON.pdf'

Quarantining:  10%|█         | 55/527 [00:05<00:49,  9.55it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\FOTISMOS\IF-01_FOTISMOS_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-01_FOTISMOS_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-01_FOTISMOS_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\FOTISMOS\IF-02_FOTISMOS_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-02_FOTISMOS_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-02_FOTISMOS_PLANS-LEVEL B.pdf'

Quarantining:  11%|█         | 57/527 [00:05<00:48,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\FOTISMOS\IF-03_FOTISMOS_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-03_FOTISMOS_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-03_FOTISMOS_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\FOTISMOS\IF-04_FOTISMOS_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-04_FOTISMOS_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-04_FOTISMOS_PLANS-LEVEL D.pdf'

Quarantining:  11%|█▏        | 60/527 [00:06<00:48,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\FOTISMOS\IF-05_FOTISMOS_PLANS-DOMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-05_FOTISMOS_PLANS-DOMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\FOTISMOS\\IF-05_FOTISMOS_PLANS-DOMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\GEIOSEIS-ANTIKERAYNIKH\GA-01_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-01_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-01_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\GEIOSEIS-ANTIKERAYNIKH\GA-02_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-02_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-02_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL B.pdf'

Quarantining:  12%|█▏        | 62/527 [00:06<00:47,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\GEIOSEIS-ANTIKERAYNIKH\GA-03_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-03_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-03_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\GEIOSEIS-ANTIKERAYNIKH\GA-04_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-04_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-04_GEIOSEIS-ANTIKERAYNIKH_PLANS-LEVEL D.pdf'

Quarantining:  12%|█▏        | 65/527 [00:06<00:47,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\GEIOSEIS-ANTIKERAYNIKH\GA-05_GEIOSEIS-ANTIKERAYNIKH_PLANS-DOMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-05_GEIOSEIS-ANTIKERAYNIKH_PLANS-DOMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\GEIOSEIS-ANTIKERAYNIKH\\GA-05_GEIOSEIS-ANTIKERAYNIKH_PLANS-DOMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HLEKTRIKOI PINAKES\HP-01_HLEKTRIKOI PINAKES-UPS & MASTERPLAN.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-01_HLEKTRIKOI PINAKES-UPS & MASTERPLAN.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-01_HLEKTRIKOI PINAKES-UPS & MASTERPLAN.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HLEKTRIKOI PINAKES\HP-02_HLEKTRIKOI PINAKES-VRAXIONAS 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-02_HLEKTRIKOI PINAKES-VRAXIONAS 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-02_HLEKTRIKOI PINAKES-VRAXIONAS 01.pdf'

Quarantining:  13%|█▎        | 67/527 [00:06<00:47,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HLEKTRIKOI PINAKES\HP-03_HLEKTRIKOI PINAKES-VRAXIONAS 02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-03_HLEKTRIKOI PINAKES-VRAXIONAS 02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-03_HLEKTRIKOI PINAKES-VRAXIONAS 02.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HLEKTRIKOI PINAKES\HP-04_HLEKTRIKOI PINAKES-VRAXIONAS 03.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-04_HLEKTRIKOI PINAKES-VRAXIONAS 03.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-04_HLEKTRIKOI PINAKES-VRAXIONAS 03.pdf'

Quarantining:  13%|█▎        | 69/527 [00:07<00:47,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HLEKTRIKOI PINAKES\HP-05_HLEKTRIKOI PINAKES-VRAXIONAS 04.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-05_HLEKTRIKOI PINAKES-VRAXIONAS 04.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HLEKTRIKOI PINAKES\\HP-05_HLEKTRIKOI PINAKES-VRAXIONAS 04.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\APWLEIES KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 1.pdf'

Quarantining:  14%|█▎        | 72/527 [00:07<00:46,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\APWLEIES KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\APWLEIES KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\APWLEIES KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\APWLEIES KTIRIO 4.pdf'

Quarantining:  14%|█▍        | 75/527 [00:07<00:46,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLA-01_HVAC_DUCTS_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-01_HVAC_DUCTS_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-01_HVAC_DUCTS_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLA-02_HVAC_DUCTS_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-02_HVAC_DUCTS_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-02_HVAC_DUCTS_PLANS-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLA-03_HVAC_DUCTS_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-03_HVAC_DUCTS_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-03_HVAC_DUCTS_PLANS-LEVEL C.pdf'

Quarantining:  15%|█▍        | 77/527 [00:07<00:46,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLA-04_HVAC_DUCTS_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-04_HVAC_DUCTS_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLA-04_HVAC_DUCTS_PLANS-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLS-01_HVAC_PIPING_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-01_HVAC_PIPING_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-01_HVAC_PIPING_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLS-02_HVAC_PIPING_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-02_HVAC_PIPING_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-02_HVAC_PIPING_PLANS-LEVEL B.pdf'

Quarantining:  15%|█▌        | 80/527 [00:08<00:46,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLS-03_HVAC_PIPING_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-03_HVAC_PIPING_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-03_HVAC_PIPING_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\KLS-04_HVAC_PIPING_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-04_HVAC_PIPING_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\KLS-04_HVAC_PIPING_PLANS-LEVEL D.pdf'

Quarantining:  16%|█▌        | 83/527 [00:08<00:45,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\PSYKTIKA FORTIA KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\PSYKTIKA FORTIA KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\PSYKTIKA FORTIA KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 3.pdf'

Quarantining:  16%|█▋        | 86/527 [00:08<00:45,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\HVAC\PSYKTIKA FORTIA KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\HVAC\\PSYKTIKA FORTIA KTIRIO 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.1.01_KENAK_PLANS_KTIRIO_1-TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.01_KENAK_PLANS_KTIRIO_1-TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.01_KENAK_PLANS_KTIRIO_1-TOPO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.1.02_KENAK_PLANS_KTIRIO_1-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.02_KENAK_PLANS_KTIRIO_1-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.02_KENAK_PLANS_KTIRIO_1-LEVEL B.pdf'

Quarantining:  17%|█▋        | 89/527 [00:09<00:45,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.1.03_KENAK_PLANS_KTIRIO_1-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.03_KENAK_PLANS_KTIRIO_1-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.03_KENAK_PLANS_KTIRIO_1-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.1.04_KENAK_PLANS_KTIRIO_1-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.04_KENAK_PLANS_KTIRIO_1-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.04_KENAK_PLANS_KTIRIO_1-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.1.05_KENAK_PLANS_KTIRIO_1-SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.05_KENAK_PLANS_KTIRIO_1-SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.1.05_KENAK_PLANS_KTIRIO_1-SKIASEIS.pdf'

Quarantining:  17%|█▋        | 92/527 [00:09<00:44,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.2.01_KENAK_PLANS_KTIRIO_2-TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.01_KENAK_PLANS_KTIRIO_2-TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.01_KENAK_PLANS_KTIRIO_2-TOPO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.2.02_KENAK_PLANS_KTIRIO_2-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.02_KENAK_PLANS_KTIRIO_2-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.02_KENAK_PLANS_KTIRIO_2-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.2.03_KENAK_PLANS_KTIRIO_2-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.03_KENAK_PLANS_KTIRIO_2-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.03_KENAK_PLANS_KTIRIO_2-LEVEL B.pdf'

Quarantining:  18%|█▊        | 94/527 [00:09<00:44,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.2.04_KENAK_PLANS_KTIRIO_2-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.04_KENAK_PLANS_KTIRIO_2-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.04_KENAK_PLANS_KTIRIO_2-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.2.05_KENAK_PLANS_KTIRIO_2-SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.05_KENAK_PLANS_KTIRIO_2-SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.2.05_KENAK_PLANS_KTIRIO_2-SKIASEIS.pdf'

Quarantining:  18%|█▊        | 96/527 [00:09<00:44,  9.59it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.01_KENAK_PLANS_KTIRIO_3-TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.01_KENAK_PLANS_KTIRIO_3-TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.01_KENAK_PLANS_KTIRIO_3-TOPO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.02_KENAK_PLANS_KTIRIO_3-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.02_KENAK_PLANS_KTIRIO_3-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.02_KENAK_PLANS_KTIRIO_3-LEVEL A.pdf'

Quarantining:  19%|█▊        | 98/527 [00:10<00:44,  9.59it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.03_KENAK_PLANS_KTIRIO_3-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.03_KENAK_PLANS_KTIRIO_3-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.03_KENAK_PLANS_KTIRIO_3-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.04_KENAK_PLANS_KTIRIO_3-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.04_KENAK_PLANS_KTIRIO_3-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.04_KENAK_PLANS_KTIRIO_3-LEVEL C.pdf'

Quarantining:  19%|█▉        | 101/527 [00:10<00:44,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.05_KENAK_PLANS_KTIRIO_3-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.05_KENAK_PLANS_KTIRIO_3-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.05_KENAK_PLANS_KTIRIO_3-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.3.06_KENAK_PLANS_KTIRIO_3-SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.06_KENAK_PLANS_KTIRIO_3-SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.3.06_KENAK_PLANS_KTIRIO_3-SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.4.01_KENAK_PLANS_KTIRIO_4-TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.01_KENAK_PLANS_KTIRIO_4-TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.01_KENAK_PLANS_KTIRIO_4-TOPO.pdf'

Quarantining:  20%|█▉        | 103/527 [00:10<00:45,  9.35it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.4.02_KENAK_PLANS_KTIRIO_4-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.02_KENAK_PLANS_KTIRIO_4-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.02_KENAK_PLANS_KTIRIO_4-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.4.03_KENAK_PLANS_KTIRIO_4-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.03_KENAK_PLANS_KTIRIO_4-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.03_KENAK_PLANS_KTIRIO_4-LEVEL C.pdf'

Quarantining:  20%|██        | 106/527 [00:10<00:44,  9.55it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\ENAK.4.04_KENAK_PLANS_KTIRIO_4-SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.04_KENAK_PLANS_KTIRIO_4-SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\ENAK.4.04_KENAK_PLANS_KTIRIO_4-SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\MELETH KENAK KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\MELETH KENAK KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 2.pdf'

Quarantining:  20%|██        | 108/527 [00:11<00:43,  9.64it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\MELETH KENAK KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KENAK\MELETH KENAK KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KENAK\\MELETH KENAK KTIRIO 4.pdf'

Quarantining:  21%|██        | 111/527 [00:11<00:42,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KINHSH\HLEKTRIKA TEXNIKH PERIGRAFH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\HLEKTRIKA TEXNIKH PERIGRAFH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\HLEKTRIKA TEXNIKH PERIGRAFH.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KINHSH\IK-01_KINHSH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-01_KINHSH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-01_KINHSH_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KINHSH\IK-02_KINHSH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-02_KINHSH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-02_KINHSH_PLANS-LEVEL B.pdf'

Quarantining:  21%|██▏       | 113/527 [00:11<00:42,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KINHSH\IK-03_KINHSH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-03_KINHSH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-03_KINHSH_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\KINHSH\IK-04_KINHSH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-04_KINHSH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\KINHSH\\IK-04_KINHSH_PLANS-LEVEL D.pdf'

Quarantining:  22%|██▏       | 116/527 [00:12<00:42,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\PISINES\KD-01_PISINES_PLANS-DIATAKSH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-01_PISINES_PLANS-DIATAKSH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-01_PISINES_PLANS-DIATAKSH.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\PISINES\KD-02_PISINES-ESOTERIKH PISINA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-02_PISINES-ESOTERIKH PISINA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-02_PISINES-ESOTERIKH PISINA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\PISINES\KD-03_PISINES-EKSOTERIKES PISINES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-03_PISINES-EKSOTERIKES PISINES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\KD-03_PISINES-EKSOTERIKES PISINES.pdf'

Quarantining:  22%|██▏       | 118/527 [00:12<00:45,  9.09it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\PISINES\TEYXOS HM MELETHS KOLYMNHTIKWN DEKSAMENWN.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\TEYXOS HM MELETHS KOLYMNHTIKWN DEKSAMENWN.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\PISINES\\TEYXOS HM MELETHS KOLYMNHTIKWN DEKSAMENWN.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\TEYXOS YDREYSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\TEYXOS YDREYSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\TEYXOS YDREYSHS.pdf'

Quarantining:  23%|██▎       | 121/527 [00:12<00:42,  9.49it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\YDR-01_YDREYSH_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-01_YDREYSH_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-01_YDREYSH_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\YDR-02_YDREYSH_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-02_YDREYSH_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-02_YDREYSH_PLANS-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\YDR-03_YDREYSH_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-03_YDREYSH_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-03_YDREYSH_PLANS-LEVEL C.pdf'

Quarantining:  23%|██▎       | 123/527 [00:12<00:41,  9.62it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\YDR-04_YDREYSH_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-04_YDREYSH_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-04_YDREYSH_PLANS-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YDREYSH\YDR-05_YDREYSH_DIAGRAM.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-05_YDREYSH_DIAGRAM.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YDREYSH\\YDR-05_YDREYSH_DIAGRAM.pdf'

Quarantining:  24%|██▍       | 126/527 [00:13<00:41,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΜΕΛΕΤΕΣ\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\PDF\YPOSTATHMOS\YS-01_YPOSTATHMOS_DIAGR.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YPOSTATHMOS\\YS-01_YPOSTATHMOS_DIAGR.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΜΕΛΕΤΕΣ\\ΣΧΕΔΙΑ_ΜΕΛΕΤΩΝ\\PDF\\YPOSTATHMOS\\YS-01_YPOSTATHMOS_DIAGR.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\.DS_Store'

Quarantining:  24%|██▍       | 128/527 [00:13<00:41,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\HVAC\21011_DUCTS_PLANS_EFARM01.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\21011_DUCTS_PLANS_EFARM01.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\21011_DUCTS_PLANS_EFARM01.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\HVAC\21011_PIPING_PLANS_EFARM01.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\21011_PIPING_PLANS_EFARM01.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\21011_PIPING_PLANS_EFARM01.dwg'

Quarantining:  25%|██▍       | 130/527 [00:13<00:40,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\HVAC\Drawing1.dwl -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\HVAC\Drawing1.dwl2 -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl2' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl2'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\YDREYSH\21011_YDREYSH_PLANS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\YDREYSH\\21011_YDREYSH_PLANS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS _ ΣΩΛΗΝΩΣΕΙΣ ΚΑΙ ΑΕΡΑΓΩΓΟΙ\\YDREYSH\\21011_YDREYSH_PLANS.dwg'

Quarantining:  25%|██▌       | 133/527 [00:13<00:40,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\21011_ISXYRA_PLANS.dwl -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\21011_ISXYRA_PLANS.dwl' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\21011_ISXYRA_PLANS.dwl'

Quarantining:  26%|██▌       | 136/527 [00:14<00:40,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\DWG\21011_ASTHENH_PLANS_EFARM_01.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\DWG\\21011_ASTHENH_PLANS_EFARM_01.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\DWG\\21011_ASTHENH_PLANS_EFARM_01.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_ASTHENH_DIAGRAM_EFARM_01-DIAGRAM.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_DIAGRAM_EFARM_01-DIAGRAM.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_DIAGRAM_EFARM_01-DIAGRAM.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_ASTHENH_PLANS_EFARM_01-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL A.pdf'

Quarantining:  26%|██▌       | 138/527 [00:14<00:39,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_ASTHENH_PLANS_EFARM_01-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_ASTHENH_PLANS_EFARM_01-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL C.pdf'

Quarantining:  27%|██▋       | 140/527 [00:14<00:39,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_ASTHENH_PLANS_EFARM_01-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_ASTHENH_PLANS_EFARM_01-LEVEL D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ASTHENH\PDF\21011_SECURITY_DIAGRAM_EFARM_01-DIAGRAM.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_SECURITY_DIAGRAM_EFARM_01-DIAGRAM.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ASTHENH\\PDF\\21011_SECURITY_DIAGRAM_EFARM_01-DIAGRAM.pdf'

Quarantining:  27%|██▋       | 143/527 [00:14<00:39,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\HLEKTRIKOI PINAKES\PDF\21011_HLEKTRIKOI PINAKES-HP_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\HLEKTRIKOI PINAKES\PDF\21011_HLEKTRIKOI PINAKES-HP_02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_02.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\HLEKTRIKOI PINAKES\PDF\21011_HLEKTRIKOI PINAKES-HP_03.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_03.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_03.pdf'

Quarantining:  28%|██▊       | 146/527 [00:15<00:39,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\HLEKTRIKOI PINAKES\PDF\21011_HLEKTRIKOI PINAKES-HP_04.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_04.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_04.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\HLEKTRIKOI PINAKES\PDF\21011_HLEKTRIKOI PINAKES-HP_05.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_05.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\HLEKTRIKOI PINAKES\\PDF\\21011_HLEKTRIKOI PINAKES-HP_05.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ISXYRA\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\.DS_Store'

Quarantining:  28%|██▊       | 148/527 [00:15<00:38,  9.75it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ISXYRA\PDF\21011_ISXYRA_PLANS-LEVEL A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ISXYRA\PDF\21011_ISXYRA_PLANS-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL B.pdf'

Quarantining:  28%|██▊       | 150/527 [00:15<00:38,  9.76it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ISXYRA\PDF\21011_ISXYRA_PLANS-LEVEL C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\ISXYRA\PDF\21011_ISXYRA_PLANS-LEVEL D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\ISXYRA\\PDF\\21011_ISXYRA_PLANS-LEVEL D.pdf'

Quarantining:  29%|██▉       | 152/527 [00:15<00:39,  9.44it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\YPOSTATHMOS\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\YPOSTATHMOS\PDF\21011_YPOSTATHMOS_DIAGR_EFARM_01-HP.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\PDF\\21011_YPOSTATHMOS_DIAGR_EFARM_01-HP.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\PDF\\21011_YPOSTATHMOS_DIAGR_EFARM_01-HP.pdf'

Quarantining:  29%|██▉       | 155/527 [00:16<00:38,  9.63it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\YPOSTATHMOS\PDF\21011_YPOSTATHMOS_PLANS_EFARM_01-LEVEL B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\PDF\\21011_YPOSTATHMOS_PLANS_EFARM_01-LEVEL B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\YPOSTATHMOS\\PDF\\21011_YPOSTATHMOS_PLANS_EFARM_01-LEVEL B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\_XREF\21011_XR_PIN_EFARM.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PIN_EFARM.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PIN_EFARM.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\_XREF\21011_XR_PIN_EFARM.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PIN_EFARM.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PIN_EFARM.dwg'

Quarantining:  30%|██▉       | 158/527 [00:16<00:38,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\_XREF\21011_XR_PLANS_EFARM.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PLANS_EFARM.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\GKA_ENGINEERS_ΗΜ_ΕΦΑΡΜΟΓΕΣ\\_XREF\\21011_XR_PLANS_EFARM.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\Thumbs.db'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\ARCHITECTURAL PLANS_P&F_17_10_2025.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ARCHITECTURAL PLANS_P&F_17_10_2025.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ARCHITECTURAL PLANS_P&F_17_10_2025.bak'

Quarantining:  30%|███       | 160/527 [00:16<00:37,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\ΜΕΛΕΤΗ ΦΩΤΙΣΜΟΥ ΒΡΑΧΙΟΝΑΣ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΜΕΛΕΤΗ ΦΩΤΙΣΜΟΥ ΒΡΑΧΙΟΝΑΣ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΜΕΛΕΤΗ ΦΩΤΙΣΜΟΥ ΒΡΑΧΙΟΝΑΣ 01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\ΠΙΝΑΚΑΣ ΔΩΜΑΤΙΩΝ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΠΙΝΑΚΑΣ ΔΩΜΑΤΙΩΝ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΠΙΝΑΚΑΣ ΔΩΜΑΤΙΩΝ.pdf'

Quarantining:  31%|███       | 162/527 [00:16<00:37,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\ΠΙΝΑΚΑΣ ΞΥΛΟΥΡΓΙΚΩΝ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΠΙΝΑΚΑΣ ΞΥΛΟΥΡΓΙΚΩΝ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΠΙΝΑΚΑΣ ΞΥΛΟΥΡΓΙΚΩΝ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\ΣΧΕΔΙΑ ΞΥΛΙΝΩΝ ΚΑΤΑΣΚΕΥΩΝ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΣΧΕΔΙΑ ΞΥΛΙΝΩΝ ΚΑΤΑΣΚΕΥΩΝ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\ΣΧΕΔΙΑ ΞΥΛΙΝΩΝ ΚΑΤΑΣΚΕΥΩΝ.dwg'

Quarantining:  31%|███       | 164/527 [00:16<00:37,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\PDF_ΚΑΤΟΨΕΩΝ\PDF_ΚΑΤΟΨΗ_Α_ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Α_ΣΤΑΘΜΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Α_ΣΤΑΘΜΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\PDF_ΚΑΤΟΨΕΩΝ\PDF_ΚΑΤΟΨΗ_Β_ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Β_ΣΤΑΘΜΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Β_ΣΤΑΘΜΗΣ.pdf'

Quarantining:  32%|███▏      | 167/527 [00:17<00:37,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\PDF_ΚΑΤΟΨΕΩΝ\PDF_ΚΑΤΟΨΗ_Γ_ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Γ_ΣΤΑΘΜΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Γ_ΣΤΑΘΜΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\PDF_ΚΑΤΟΨΕΩΝ\PDF_ΚΑΤΟΨΗ_Δ_ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Δ_ΣΤΑΘΜΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\PDF_ΚΑΤΟΨΕΩΝ\\PDF_ΚΑΤΟΨΗ_Δ_ΣΤΑΘΜΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf'

Quarantining:  32%|███▏      | 169/527 [00:17<00:36,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf'

Quarantining:  33%|███▎      | 172/527 [00:17<00:36,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΧΩΡΟΣ_ΠΙΣΙΝΑ_ΣΠΑ_ΣΤΑΘΜΗ_Α.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΧΩΡΟΣ_ΠΙΣΙΝΑ_ΣΠΑ_ΣΤΑΘΜΗ_Α.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΧΩΡΟΣ_ΠΙΣΙΝΑ_ΣΠΑ_ΣΤΑΘΜΗ_Α.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΒΡΑΧΙΟΝΑ 1\40_CS_01_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_01_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_01_01.pdf'

Quarantining:  33%|███▎      | 175/527 [00:18<00:36,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΒΡΑΧΙΟΝΑ 1\40_CS_02_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_02_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_02_01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΒΡΑΧΙΟΝΑ 1\40_CS_02_02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_02_02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\40_CS_02_02.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΒΡΑΧΙΟΝΑ 1\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf'

Quarantining:  34%|███▍      | 178/527 [00:18<00:36,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΒΡΑΧΙΟΝΑ 1\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΒΡΑΧΙΟΝΑ 1\\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ _ΚΑΤΟΨΕΙΣ ΔΩΜΑΤΙΩΝ - ΑΝΑΠΤΥΓΜΑΤΑ\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F_3D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ _ΚΑΤΟΨΕΙΣ ΔΩΜΑΤΙΩΝ - ΑΝΑΠΤΥΓΜΑΤΑ\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F_3D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ _ΚΑΤΟΨΕΙΣ ΔΩΜΑΤΙΩΝ - ΑΝΑΠΤΥΓΜΑΤΑ\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F_3D.pdf'

Quarantining:  34%|███▍      | 180/527 [00:18<00:35,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\60_WA_01_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\60_WA_01_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\60_WA_01_01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\ARCHITECTURAL PLANS_P&F_2025.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ARCHITECTURAL PLANS_P&F_2025.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ARCHITECTURAL PLANS_P&F_2025.dwg'

Quarantining:  35%|███▍      | 183/527 [00:18<00:35,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\SPA ΜΕ ΔΙΑΣΤΑΣΕΙΣ\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΔΩΜΑΤΙΑ_SPA\ΒΡΑΧΙΟΝΑΣ 1\PDF ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 1     19.06.2025\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01_REV_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\ΒΡΑΧΙΟΝΑΣ 1\\PDF ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 1     19.06.2025\\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01_REV_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΔΩΜΑΤΙΑ_SPA\\ΒΡΑΧΙΟΝΑΣ 1\\PDF ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 1     19.06.2025\\ΣΧΕΔΙΑ ΒΡΑΧΙΟΝΑ 01_REV_01.pdf'

Quarantining:  35%|███▌      | 185/527 [00:19<00:35,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\40_CS_02_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\40_CS_02_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\40_CS_02_01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\40_CS_02_02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\40_CS_02_02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\40_CS_02_02.pdf'

Quarantining:  36%|███▌      | 188/527 [00:19<00:34,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\ARCHITECTURAL PLANS_P&F_02_10_2025.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ARCHITECTURAL PLANS_P&F_02_10_2025.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ARCHITECTURAL PLANS_P&F_02_10_2025.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΔΙΑΦΟΡΑ_ΔΙΑΣΠΑΡΤΑ\\ΠΑΡΟΥΣΙΑΣΗ_ΒΡΑΧΙΟΝΑ_1_ΦΩΤΙΣΜΟΣ\\ΠΙΝΑΚΑΣ ΦΩΤΙΣΤΙΚΩΝ_ΒΡΑΧΙΟΝΑΣ 01.pdf'

Quarantining:  36%|███▌      | 191/527 [00:19<00:34,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\ΠΡΟΤΑΣΗ ΓΙΑ ΤΗΝ ΠΕΤΡΑ\11_12_2025_ΠΡΟΤΑΣΗ\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΠΡΟΤΑΣΗ ΓΙΑ ΤΗΝ ΠΕΤΡΑ\\11_12_2025_ΠΡΟΤΑΣΗ\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ ΕΡΓΟΥ\\ΡΟΗ_ΝΕΩΝ_ΜΕΛΕΤΩΝ\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΚΕΚΤΟΝΙΚΑ\\ΠΡΟΤΑΣΗ ΓΙΑ ΤΗΝ ΠΕΤΡΑ\\11_12_2025_ΠΡΟΤΑΣΗ\\Thumbs.db'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\EFARMOGH\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\EFARMOGH\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\EFARMOGH\\.DS_Store'

Quarantining:  37%|███▋      | 193/527 [00:19<00:34,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\EFARMOGH\3d DRAFT\Thumbs.db -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\EFARMOGH\\3d DRAFT\\Thumbs.db' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\EFARMOGH\\3d DRAFT\\Thumbs.db'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\SONADO _ 13 05 2025\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\SONADO _ 13 05 2025\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\SONADO _ 13 05 2025\\.DS_Store'

Quarantining:  37%|███▋      | 196/527 [00:20<00:34,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\01_SONADO_OITYLO_ANELKYSTHRAS_SXEDIO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\\01_SONADO_OITYLO_ANELKYSTHRAS_SXEDIO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\\01_SONADO_OITYLO_ANELKYSTHRAS_SXEDIO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\02_SONADO_OITYLO_ANELKYSTHRAS_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\\02_SONADO_OITYLO_ANELKYSTHRAS_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\150 ΜΕΛΕΤΗ ΑΝΥΨΩΤΙΚΩΝ ΣΥΣΤΗΜΑΤΩΝ\\02_SONADO_OITYLO_ANELKYSTHRAS_TEYXOS.pdf'

Quarantining:  38%|███▊      | 199/527 [00:20<00:33,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf'

Quarantining:  38%|███▊      | 202/527 [00:20<00:34,  9.46it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf'

Quarantining:  39%|███▊      | 204/527 [00:21<00:33,  9.60it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf'

Quarantining:  39%|███▉      | 208/527 [00:21<00:32,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf'

Quarantining:  40%|████      | 211/527 [00:21<00:32,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf'

Quarantining:  40%|████      | 213/527 [00:22<00:32,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\151 ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\155 ΣΤΑΤΙΣΤΙΚΟ ΔΕΛΤΙΟ ΕΛΣΤΑΤ\01_SONADO_OITYLO_STATISTIKO DELTIO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\155 ΣΤΑΤΙΣΤΙΚΟ ΔΕΛΤΙΟ ΕΛΣΤΑΤ\\01_SONADO_OITYLO_STATISTIKO DELTIO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\155 ΣΤΑΤΙΣΤΙΚΟ ΔΕΛΤΙΟ ΕΛΣΤΑΤ\\01_SONADO_OITYLO_STATISTIKO DELTIO.pdf'

Quarantining:  41%|████      | 215/527 [00:22<00:32,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\19 ΜΕΛΕΤΗ ΠΕΡΙΒΑΛΛΟΝΤΙΚΩΝ ΕΠΙΠΤΩΣΕΩΝ\01_SONADO_OITYLO_PPD.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\19 ΜΕΛΕΤΗ ΠΕΡΙΒΑΛΛΟΝΤΙΚΩΝ ΕΠΙΠΤΩΣΕΩΝ\\01_SONADO_OITYLO_PPD.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\19 ΜΕΛΕΤΗ ΠΕΡΙΒΑΛΛΟΝΤΙΚΩΝ ΕΠΙΠΤΩΣΕΩΝ\\01_SONADO_OITYLO_PPD.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\01_SONADO_OITYLO_KATOPSH ST A'.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_KATOPSH ST A'.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_KATOPSH ST A'.pdf"

Quarantining:  41%|████      | 217/527 [00:22<00:31,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\02_SONADO_OITYLO_KATOPSH ST B'.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_KATOPSH ST B'.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_KATOPSH ST B'.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\03_SONADO_OITYLO_KATOPSH ST C'.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_KATOPSH ST C'.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_KATOPSH ST C'.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\04_SONADO_OITYLO_KATOPSH ST D'.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_KATOPSH ST D'.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_KATOPSH ST D'.pdf"

Quarantining:  42%|████▏     | 221/527 [00:22<00:31,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\05_SONADO_OITYLO_KATOPSH DWMATWN.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_KATOPSH DWMATWN.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_KATOPSH DWMATWN.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\06_SONADO_OITYLO_OPSEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_OPSEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_OPSEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\07_SONADO_OITYLO_TOMES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_TOMES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_TOMES.pdf'

Quarantining:  42%|████▏     | 223/527 [00:23<00:31,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\08_SONADO_OITYLO_DIAGRAMMA AKALYPTOY.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_DIAGRAMMA AKALYPTOY.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_DIAGRAMMA AKALYPTOY.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\09_SONADO_OITYLO_MELETH PROSVASIMOTHTAS AMEA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_MELETH PROSVASIMOTHTAS AMEA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\24 ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_MELETH PROSVASIMOTHTAS AMEA.pdf'

Quarantining:  43%|████▎     | 225/527 [00:23<00:31,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf'

Quarantining:  43%|████▎     | 228/527 [00:23<00:30,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf'

Quarantining:  44%|████▍     | 231/527 [00:23<00:30,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf'

Quarantining:  44%|████▍     | 234/527 [00:24<00:30,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf'

Quarantining:  45%|████▍     | 237/527 [00:24<00:29,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf'

Quarantining:  46%|████▌     | 240/527 [00:24<00:29,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf'

Quarantining:  46%|████▌     | 242/527 [00:25<00:29,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf'

Quarantining:  46%|████▋     | 245/527 [00:25<00:28,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf'

Quarantining:  47%|████▋     | 247/527 [00:25<00:28,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf'

Quarantining:  47%|████▋     | 249/527 [00:25<00:29,  9.53it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf'

Quarantining:  48%|████▊     | 251/527 [00:25<00:29,  9.44it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf'

Quarantining:  48%|████▊     | 255/527 [00:26<00:28,  9.62it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf'

Quarantining:  49%|████▉     | 257/527 [00:26<00:27,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf'

Quarantining:  49%|████▉     | 260/527 [00:26<00:27,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf'

Quarantining:  50%|████▉     | 262/527 [00:27<00:29,  8.88it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf'

Quarantining:  50%|█████     | 264/527 [00:27<00:28,  9.31it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf'

Quarantining:  50%|█████     | 266/527 [00:27<00:27,  9.54it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf'

Quarantining:  51%|█████     | 269/527 [00:27<00:26,  9.62it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf'

Quarantining:  52%|█████▏    | 272/527 [00:28<00:26,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\31_SONADO_OITYLO_PISINES_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\31_SONADO_OITYLO_PISINES_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\26 ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\31_SONADO_OITYLO_PISINES_TEYXOS.pdf'

Quarantining:  52%|█████▏    | 274/527 [00:28<00:26,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf'

Quarantining:  53%|█████▎    | 277/527 [00:28<00:25,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf'

Quarantining:  53%|█████▎    | 280/527 [00:29<00:25,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf'

Quarantining:  54%|█████▎    | 282/527 [00:29<00:25,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf'

Quarantining:  54%|█████▍    | 285/527 [00:29<00:24,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf'

Quarantining:  54%|█████▍    | 287/527 [00:29<00:24,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf'

Quarantining:  55%|█████▌    | 290/527 [00:30<00:24,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\27 ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\01_SONADO_OITYLO_KENAK_KTIRIO_1_TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\01_SONADO_OITYLO_KENAK_KTIRIO_1_TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\01_SONADO_OITYLO_KENAK_KTIRIO_1_TOPO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\02_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\02_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\02_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI B.pdf'

Quarantining:  55%|█████▌    | 292/527 [00:30<00:24,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\03_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\03_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\03_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\04_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\04_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\04_SONADO_OITYLO_KENAK_KTIRIO_1_STATHMI D.pdf'

Quarantining:  56%|█████▌    | 294/527 [00:30<00:24,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\05_SONADO_OITYLO_KENAK_KTIRIO_1_SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\05_SONADO_OITYLO_KENAK_KTIRIO_1_SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\05_SONADO_OITYLO_KENAK_KTIRIO_1_SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\06_SONADO_OITYLO_KENAK_KTIRIO 2_TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\06_SONADO_OITYLO_KENAK_KTIRIO 2_TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\06_SONADO_OITYLO_KENAK_KTIRIO 2_TOPO.pdf'

Quarantining:  56%|█████▋    | 297/527 [00:30<00:23,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\07_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\07_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\07_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\08_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\08_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\08_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\09_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\09_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\09_SONADO_OITYLO_KENAK_KTIRIO 2_STATHMI C.pdf'

Quarantining:  57%|█████▋    | 300/527 [00:31<00:23,  9.62it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\10_SONADO_OITYLO_KENAK_KTIRIO 2_SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\10_SONADO_OITYLO_KENAK_KTIRIO 2_SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\10_SONADO_OITYLO_KENAK_KTIRIO 2_SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\11_SONADO_OITYLO_KENAK_KTIRIO 3_TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\11_SONADO_OITYLO_KENAK_KTIRIO 3_TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\11_SONADO_OITYLO_KENAK_KTIRIO 3_TOPO.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\12_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\12_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\12_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI A.pdf'

Quarantining:  57%|█████▋    | 303/527 [00:31<00:23,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\13_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\13_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\13_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\14_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\14_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\14_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\15_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\15_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\15_SONADO_OITYLO_KENAK_KTIRIO 3_STATHMI D.pdf'

Quarantining:  58%|█████▊    | 305/527 [00:31<00:22,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\16_SONADO_OITYLO_KENAK_KTIRIO 3_SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\16_SONADO_OITYLO_KENAK_KTIRIO 3_SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\16_SONADO_OITYLO_KENAK_KTIRIO 3_SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\17_SONADO_OITYLO_KENAK_KTIRIO 4_TOPO.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\17_SONADO_OITYLO_KENAK_KTIRIO 4_TOPO.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\17_SONADO_OITYLO_KENAK_KTIRIO 4_TOPO.pdf'

Quarantining:  58%|█████▊    | 307/527 [00:31<00:25,  8.77it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\18_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\18_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\18_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\19_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\19_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\19_SONADO_OITYLO_KENAK_KTIRIO 4_STATHMI C.pdf'

Quarantining:  59%|█████▊    | 309/527 [00:32<00:24,  8.76it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\20_SONADO_OITYLO_KENAK_KTIRIO 4_SKIASEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\20_SONADO_OITYLO_KENAK_KTIRIO 4_SKIASEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\20_SONADO_OITYLO_KENAK_KTIRIO 4_SKIASEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\21_SONADO_OITYLO_KENAK_KTIRIO 1_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\21_SONADO_OITYLO_KENAK_KTIRIO 1_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\21_SONADO_OITYLO_KENAK_KTIRIO 1_TEYXOS.pdf'

Quarantining:  59%|█████▉    | 311/527 [00:32<00:23,  9.25it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\22_SONADO_OITYLO_KENAK_KTIRIO 2_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\22_SONADO_OITYLO_KENAK_KTIRIO 2_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\22_SONADO_OITYLO_KENAK_KTIRIO 2_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\23_SONADO_OITYLO_KENAK_KTIRIO 3_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\23_SONADO_OITYLO_KENAK_KTIRIO 3_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\23_SONADO_OITYLO_KENAK_KTIRIO 3_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\24_SONADO_OITYLO_KENAK_KTIRIO 4_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\24_SONADO_OITYLO_KENAK_KTIRIO 4_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\28 ΜΕΛΕΤΗ ΕΝΕΡΓΕΙΑΚΗΣ ΑΠΟΔΟΣΗΣ ΚΤΗΡΙΟΥ\\24_SONADO_OITYLO_KENAK_KTIRIO 4_TEYXOS.pdf'

Quarantining:  60%|█████▉    | 314/527 [00:32<00:22,  9.54it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\01_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\01_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\01_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\02_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\02_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\02_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 2.pdf'

Quarantining:  60%|██████    | 317/527 [00:32<00:21,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\03_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\03_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\03_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\04_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\04_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\04_SONADO_OITYLO_ENTYPO ENERGHTIKHS BRAXIONAS 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\05_SONADO_OITYLO_ENERG PYRO_TEXNIKH PERIGRAFH MONIMWN SYSTHMATON.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\05_SONADO_OITYLO_ENERG PYRO_TEXNIKH PERIGRAFH MONIMWN SYSTHMATON.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\05_SONADO_OITYLO_ENERG PYRO_TEXNIKH PERIGRAFH MONIMWN SYSTHMATON.pdf'

Quarantining:  61%|██████    | 319/527 [00:33<00:21,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\06_SONADO_OITYLO_ENERG PYRO_PARARTHMA 2_YPOLOGISMOI.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\06_SONADO_OITYLO_ENERG PYRO_PARARTHMA 2_YPOLOGISMOI.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\06_SONADO_OITYLO_ENERG PYRO_PARARTHMA 2_YPOLOGISMOI.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\07_SONADO_OITYLO_PYROSVESH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\07_SONADO_OITYLO_PYROSVESH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\07_SONADO_OITYLO_PYROSVESH_STATHMI A.pdf'

Quarantining:  61%|██████    | 321/527 [00:33<00:21,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\08_SONADO_OITYLO_PYROSVESH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\08_SONADO_OITYLO_PYROSVESH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\08_SONADO_OITYLO_PYROSVESH_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\09_SONADO_OITYLO_PYROSVESH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\09_SONADO_OITYLO_PYROSVESH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\09_SONADO_OITYLO_PYROSVESH_STATHMI C.pdf'

Quarantining:  61%|██████▏   | 324/527 [00:33<00:21,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\10_SONADO_OITYLO_PYROSVESH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\10_SONADO_OITYLO_PYROSVESH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\10_SONADO_OITYLO_PYROSVESH_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\11_SONADO_OITYLO_PYRANIXNEYSH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\11_SONADO_OITYLO_PYRANIXNEYSH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\11_SONADO_OITYLO_PYRANIXNEYSH_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\12_SONADO_OITYLO_PYRANIXNEYSH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\12_SONADO_OITYLO_PYRANIXNEYSH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\12_SONADO_OITYLO_PYRANIXNEYSH_STATHMI B.pdf'

Quarantining:  62%|██████▏   | 326/527 [00:33<00:21,  9.43it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\13_SONADO_OITYLO_PYRANIXNEYSH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\13_SONADO_OITYLO_PYRANIXNEYSH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\13_SONADO_OITYLO_PYRANIXNEYSH_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\14_SONADO_OITYLO_PYRANIXNEYSH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\14_SONADO_OITYLO_PYRANIXNEYSH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\29 ΜΕΛΕΤΗ ΕΝΕΡΓΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\14_SONADO_OITYLO_PYRANIXNEYSH_STATHMI D.pdf'

Quarantining:  62%|██████▏   | 328/527 [00:34<00:22,  9.02it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\01_SONADO_OITYLO_PAΤΗΙTIKH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\01_SONADO_OITYLO_PAΤΗΙTIKH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\01_SONADO_OITYLO_PAΤΗΙTIKH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\02_SONADO_OITYLO_PATHITIKH_VRAXIONAS 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\02_SONADO_OITYLO_PATHITIKH_VRAXIONAS 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\02_SONADO_OITYLO_PATHITIKH_VRAXIONAS 1.pdf'

Quarantining:  63%|██████▎   | 330/527 [00:34<00:21,  9.36it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\03_SONADO_OITYLO_PATHITIKH_VRAXIONAS 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\03_SONADO_OITYLO_PATHITIKH_VRAXIONAS 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\03_SONADO_OITYLO_PATHITIKH_VRAXIONAS 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\04_SONADO_OITYLO_PATHITIKH_VRAXIONAS 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\04_SONADO_OITYLO_PATHITIKH_VRAXIONAS 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\04_SONADO_OITYLO_PATHITIKH_VRAXIONAS 3.pdf'

Quarantining:  63%|██████▎   | 333/527 [00:34<00:20,  9.55it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\05_SONADO_OITYLO_PATHITIKH_VRAXIONAS 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\05_SONADO_OITYLO_PATHITIKH_VRAXIONAS 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\291 ΜΕΛΕΤΗ ΠΑΘΗΤΙΚΗΣ ΠΥΡΟΠΡΟΣΤΑΣΙΑΣ\\05_SONADO_OITYLO_PATHITIKH_VRAXIONAS 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\01_SONADO_OITYLO_SDA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\01_SONADO_OITYLO_SDA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\01_SONADO_OITYLO_SDA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\02_SONADO_OITYLO_TEXNIKH EKTHESI SDA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\02_SONADO_OITYLO_TEXNIKH EKTHESI SDA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\02_SONADO_OITYLO_TEXNIKH EKTHESI SDA.pdf'

Quarantining:  64%|██████▎   | 335/527 [00:34<00:19,  9.61it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΑΔΕΙΑ\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\03_SONADO_OITYLO_SYMVASH SDA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\03_SONADO_OITYLO_SYMVASH SDA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΑΔΕΙΑ\\56 ΣΧΕΔΙΟ ΔΙΑΧΕΙΡΙΣΗΣ ΑΠΟΒΛΗΤΩΝ (ΣΔΑ) & ΣΥΜΒΑΣΗ ΔΙΑΧΕΙΡΙΣΤΗ ΑΕΚΚ\\03_SONADO_OITYLO_SYMVASH SDA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\.DS_Store'

Quarantining:  64%|██████▍   | 337/527 [00:35<00:21,  8.64it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg'

Quarantining:  64%|██████▍   | 339/527 [00:35<00:20,  9.15it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\.DS_Store'

Quarantining:  65%|██████▍   | 341/527 [00:35<00:19,  9.44it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg'

Quarantining:  65%|██████▌   | 343/527 [00:35<00:19,  9.58it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg'

Quarantining:  65%|██████▌   | 345/527 [00:35<00:18,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg'

Quarantining:  66%|██████▌   | 348/527 [00:36<00:19,  9.40it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak'

Quarantining:  67%|██████▋   | 351/527 [00:36<00:18,  9.59it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.dwg'

Quarantining:  67%|██████▋   | 353/527 [00:36<00:18,  9.64it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf'

Quarantining:  68%|██████▊   | 356/527 [00:37<00:17,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf'

Quarantining:  68%|██████▊   | 359/527 [00:37<00:17,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.pdf'

Quarantining:  69%|██████▊   | 361/527 [00:37<00:17,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg'

Quarantining:  69%|██████▉   | 364/527 [00:37<00:16,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'

Quarantining:  69%|██████▉   | 366/527 [00:38<00:17,  9.36it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  70%|██████▉   | 368/527 [00:38<00:17,  9.13it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg'

Quarantining:  70%|███████   | 371/527 [00:38<00:16,  9.51it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  71%|███████   | 373/527 [00:38<00:16,  9.58it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  71%|███████▏  | 376/527 [00:39<00:15,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'

Quarantining:  72%|███████▏  | 378/527 [00:39<00:15,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'

Quarantining:  72%|███████▏  | 380/527 [00:39<00:15,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf"

Quarantining:  72%|███████▏  | 382/527 [00:39<00:14,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf'

Quarantining:  73%|███████▎  | 385/527 [00:40<00:14,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf"

Quarantining:  73%|███████▎  | 387/527 [00:40<00:14,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΜΕΛΕΤΕΣ-ΕΦΑΡΜΟΓΗ\\ΣΤΑΤΙΚΗ_ΑΡΧΙΤΕΚΤΟΝΙΚΗ_ΜΕΛΕΤΗ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf'

Quarantining:  74%|███████▍  | 389/527 [00:40<00:14,  9.57it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\GKA_ENGINEERS_ΣΧΕΔΙΑ\2025\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\HVAC\Drawing1.dwl -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\GKA_ENGINEERS_ΣΧΕΔΙΑ\\2025\\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\GKA_ENGINEERS_ΣΧΕΔΙΑ\\2025\\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\GKA_ENGINEERS_ΣΧΕΔΙΑ\2025\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\HVAC\Drawing1.dwl2 -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\GKA_ENGINEERS_ΣΧΕΔΙΑ\\2025\\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl2' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\GKA_ENGINEERS_ΣΧΕΔΙΑ\\2025\\ΣΩΛΗΝΩΣΕΙΣ_ΑΕΡΑΓΩΓΟΙ\\HVAC\\Drawing1.dwl2'

Quarantining:  74%|███████▍  | 391/527 [00:40<00:14,  9.09it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\01_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_TEXN PERIGRAFH.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\02_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI A.pdf'

Quarantining:  75%|███████▍  | 393/527 [00:40<00:14,  9.41it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\03_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\04_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI C.pdf'

Quarantining:  75%|███████▍  | 395/527 [00:41<00:14,  9.02it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\05_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\06_SONADO_OITYLO_HLEKTRIKA_ASTHENH REVMATA_DOMATA.pdf'

Quarantining:  75%|███████▌  | 397/527 [00:41<00:13,  9.36it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\07_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_TEXN PERIGRAFH.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\08_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\09_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI B.pdf'

Quarantining:  76%|███████▌  | 401/527 [00:41<00:13,  9.63it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\10_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\11_SONADO_OITYLO_HLEKTRIKA_ISXYRA REVMATA_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\12_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI A.pdf'

Quarantining:  76%|███████▋  | 403/527 [00:41<00:12,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\13_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\14_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI C.pdf'

Quarantining:  77%|███████▋  | 405/527 [00:42<00:13,  8.95it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\15_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\16_SONADO_OITYLO_HLEKTRIKA_FOTISMOS_DOMATA.pdf'

Quarantining:  77%|███████▋  | 407/527 [00:42<00:12,  9.33it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\17_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\18_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI B.pdf'

Quarantining:  78%|███████▊  | 409/527 [00:42<00:12,  9.52it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\19_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\20_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\21_SONADO_OITYLO_HLEKTRIKA_GEIOSEIS-ANTIKERAYNIKH_DOMATA.pdf'

Quarantining:  78%|███████▊  | 413/527 [00:43<00:11,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\22_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-UPS & MASTERPLAN.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\23_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 01.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\24_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 02.pdf'

Quarantining:  79%|███████▉  | 416/527 [00:43<00:11,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\25_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 03.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\26_SONADO_OITYLO_HLEKTRIKA_HL PINAKES-VRAXIONAS 04.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\27_SONADO_OITYLO_HLEKTRIKA_YPOSTATHMOS-DIAGRAMMA.pdf'

Quarantining:  80%|███████▉  | 419/527 [00:43<00:11,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\28_SONADO_OITYLO_PISINES_PLAN_DIATAKSI.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\29_SONADO_OITYLO_PISINES_ESOTERIKH PISINA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\30_SONADO_OITYLO_PISINES_EKSOTERIKES PISINES.pdf'

Quarantining:  80%|████████  | 422/527 [00:43<00:10,  9.57it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\31_SONADO_OITYLO_PISINES_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\31_SONADO_OITYLO_PISINES_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΗΛΕΚΤΡΟΜΗΧΑΝΟΛΟΓΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ\\31_SONADO_OITYLO_PISINES_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\01_SONADO_OITYLO_APOXETEYSH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\02_SONADO_OITYLO_APOXETEYSH_STATHMI A.pdf'

Quarantining:  81%|████████  | 425/527 [00:44<00:10,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\03_SONADO_OITYLO_APOXETEYSH_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\04_SONADO_OITYLO_APOXETEYSH_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\05_SONADO_OITYLO_APOXETEYSH_STATHMI D.pdf'

Quarantining:  81%|████████  | 427/527 [00:44<00:10,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\06_SONADO_OITYLO_APOXETEYSH_STATHMI DOMATOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\07_SONADO_OITYLO_APOXETEYSH_DIAGRAMMA.pdf'

Quarantining:  82%|████████▏ | 430/527 [00:44<00:09,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\08_SONADO_OITYLO_YDREYSH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\09_SONADO_OITYLO_YDREYSH_DIAGRAMMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\10_SONADO_OITYLO_YDREYSH_STATHMI B.pdf'

Quarantining:  82%|████████▏ | 432/527 [00:45<00:09,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\11_SONADO_OITYLO_YDREYSH_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\12_SONADO_OITYLO_YDREYSH_STATHMI C.pdf'

Quarantining:  82%|████████▏ | 434/527 [00:45<00:09,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\13_SONADO_OITYLO_YDREYSH_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\14_SONADO_OITYLO_BIOLOGIKOS_PLANS.pdf'

Quarantining:  83%|████████▎ | 437/527 [00:45<00:09,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\15_SONADO_OITYLO_BIOLOGIKOS_DIAGRAMMA.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΕΣ ΥΔΡΑΥΛΙΚΩΝ ΕΓΚΑΤΑΣΤΑΣΕΩΝ & ΑΠΟΧΕΤΕΥΣΕΩΝ\\16_SONADO_OITYLO_BIOLOGIKOS_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\01_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 1.pdf'

Quarantining:  83%|████████▎ | 440/527 [00:45<00:08,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\02_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 2.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\03_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\04_SONADO_OITYLO_KLIMATISMOS_APWLEIES KTIRIO 4.pdf'

Quarantining:  84%|████████▍ | 442/527 [00:46<00:08,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\05_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 1.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\06_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 2.pdf'

Quarantining:  84%|████████▍ | 445/527 [00:46<00:08,  9.59it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\07_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 3.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\08_SONADO_OITYLO_KLIMATISMOS_PSYKTIKA FORTIA KTIRIO 4.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\09_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI A.pdf'

Quarantining:  85%|████████▍ | 447/527 [00:46<00:08,  9.64it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\10_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI B.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\11_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI C.pdf'

Quarantining:  85%|████████▌ | 450/527 [00:46<00:07,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\12_SONADO_OITYLO_KLIMATISMOS_AERAGWGOI_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\13_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI A.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\14_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI B.pdf'

Quarantining:  86%|████████▌ | 453/527 [00:47<00:07,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\15_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI C.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΜΕ ΒΑΣΗ ΤΗΝ ΟΙΚΟΔΟΜΙΚΗ ΑΔΕΙΑ_383786\\ΜΕΛΕΤΗ ΕΓΚΑΤΑΣΤΑΣΗΣ ΚΛΙΜΑΤΙΣΜΟΥ\\16_SONADO_OITYLO_KLIMATISMOS_SWLHNWSEIS_STATHMI D.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΒΡΑΧΙΟΝΑ 01.pdf'

Quarantining:  86%|████████▋ | 455/527 [00:47<00:07,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΔΩΜΑΤΙΩΝ_P&F.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΠΡΟΣ MNP\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\RENDERS\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf' -> '..\\quarantine\\run_20260302_141826\\ΠΡΟΣ MNP\\ΠΑΡΑΦΟΡΟΥ_ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ PETRA & FOS\\RENDERS\\ΠΑΡΟΥΣΙΑΣΗ ΠΙΣΙΝΑΣ_ΣΠΑ_rev_01.pdf'

Quarantining:  87%|████████▋ | 458/527 [00:47<00:07,  9.65it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl" -> "..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\.DS_Store -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\.DS_Store' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\.DS_Store'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\01_SONADO_OITYLO_STATIKA_KT01_TEYXOS.pdf'

Quarantining:  87%|████████▋ | 460/527 [00:47<00:06,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\02_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS THEMELIWSHS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\03_SONADO_OITYLO_STATIKA_KT01_XYLOTYPOS A-B-C STATHMIS.pdf'

Quarantining:  88%|████████▊ | 462/527 [00:48<00:06,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\04_SONADO_OITYLO_STATIKA_KT02_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\05_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS THEMELIWSHS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\06_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS A STATHMIS.pdf'

Quarantining:  88%|████████▊ | 465/527 [00:48<00:06,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\07_SONADO_OITYLO_STATIKA_KT02_XYLOTYPOS B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\08_SONADO_OITYLO_STATIKA_KT03_TEYXOS.pdf'

Quarantining:  89%|████████▉ | 468/527 [00:48<00:06,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\09_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\10_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS THEMELIWSHS - YPOGEIOY.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\11_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS A STATHMIS.pdf'

Quarantining:  89%|████████▉ | 470/527 [00:48<00:06,  9.11it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\12_SONADO_OITYLO_STATIKA_KT03_XYLOTYPOS B-C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\13_SONADO_OITYLO_STATIKA_KT04_TEYXOS.pdf'

Quarantining:  90%|████████▉ | 472/527 [00:49<00:05,  9.38it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\14_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS THEMELIWSHS - A STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\15_SONADO_OITYLO_STATIKA_KT04_XYLOTYPOS B-C STATHMIS.pdf'

Quarantining:  90%|████████▉ | 474/527 [00:49<00:05,  9.55it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\16_SONADO_OITYLO_STATIKA_TYPIKH STEGH_TEYXOS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\17_SONADO_OITYLO_STATIKA_TYPIKH STEGH.pdf'

Quarantining:  91%|█████████ | 477/527 [00:49<00:05,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\ΣΤΑΤΙΚΑ_DRAFT\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf' -> '..\\quarantine\\run_20260302_141826\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ_Α.Α_391720\\ΣΤΑΤΙΚΑ_DRAFT\\25 ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\18_SONADO_OITYLO_STATIKA_KTHRIO VIOLOGIKOU KATHARISMOU-DEKSAMENHS NEROU.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_OITYLO_TOMH TOIXOY KAI TOIXIOY.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_OITYLO_TOPOGRAFIKO DIAGRAMMA.dwg'

Quarantining:  91%|█████████ | 479/527 [00:49<00:04,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\SONADO_ΟΙΤΥΛΟ_ΔΙΑΓΡΑΜΜΑ ΕΚΣΚΑΦΩΝ_updated.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.bak'

Quarantining:  91%|█████████▏| 482/527 [00:50<00:04,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.dwg'

Quarantining:  92%|█████████▏| 484/527 [00:50<00:04,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.dwg'

Quarantining:  92%|█████████▏| 487/527 [00:50<00:04,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.bak'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.bak'

Quarantining:  93%|█████████▎| 489/527 [00:50<00:03,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.bak'

Quarantining:  93%|█████████▎| 491/527 [00:51<00:03,  9.22it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.bak -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.bak'

Quarantining:  94%|█████████▎| 493/527 [00:51<00:03,  9.45it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\DWG ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\01_SONADO_OITYLO_KATOPSH A STATHMIS.pdf'

Quarantining:  94%|█████████▍| 496/527 [00:51<00:03,  9.64it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\02_SONADO_OITYLO_KATOPSH B STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\03_SONADO_OITYLO_KATOPSH C STATHMIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\04_SONADO_OITYLO_KATOPSH D STATHMIS.pdf'

Quarantining:  95%|█████████▍| 499/527 [00:51<00:02,  9.67it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\05_SONADO_OITYLO_KATOPSH DOMATON.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\05_SONADO_OITYLO_KATOPSH DOMATON.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\06_SONADO_OITYLO_OPSEIS.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\06_SONADO_OITYLO_OPSEIS.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\07_SONADO_OITYLO_TOMES.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΑΡΧΙΤΕΚΤΟΝΙΚΗ ΜΕΛΕΤΗ\\PDF ΑΡΧΙΤΕΚΤΟΝΙΚΑ\\07_SONADO_OITYLO_TOMES.pdf'

Quarantining:  95%|█████████▌| 502/527 [00:52<00:02,  9.70it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  96%|█████████▌| 504/527 [00:52<00:02,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  96%|█████████▌| 507/527 [00:52<00:02,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.dwg'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.dwg'

Quarantining:  97%|█████████▋| 509/527 [00:53<00:01,  9.72it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg"

Quarantining:  97%|█████████▋| 511/527 [00:53<00:01,  9.69it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.dwl"

Quarantining:  97%|█████████▋| 513/527 [00:53<00:01,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.dwg"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\DWG ΣΤΑΤΙΚΑ\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\DWG ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.dwg'

Quarantining:  98%|█████████▊| 515/527 [00:53<00:01,  9.73it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΠΡΟΜΕΤΡΗΣΗ ΣΚΥΡΟΔΕΜΑΤΩΝ_SONADO IKE.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΠΡΟΜΕΤΡΗΣΗ ΣΚΥΡΟΔΕΜΑΤΩΝ_SONADO IKE.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΠΡΟΜΕΤΡΗΣΗ ΣΚΥΡΟΔΕΜΑΤΩΝ_SONADO IKE.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ0-01  - ΤΥΠΙΚΗ ΔΙΑΤΑΞΗ ΣΤΕΓΗΣ.pdf'

Quarantining:  98%|█████████▊| 518/527 [00:53<00:00,  9.66it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-01  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ1-02  - ΚΤΗΡΙΟ 1 ΞΥΛΟΤΥΠΟΣ Α',Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-01  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'

Quarantining:  99%|█████████▉| 521/527 [00:54<00:00,  9.68it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-02  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ2-03  - ΚΤΗΡΙΟ 2 ΞΥΛΟΤΥΠΟΣ B',Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-01  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ.pdf'

Quarantining:  99%|█████████▉| 523/527 [00:54<00:00,  9.71it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-02  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ - ΥΠΟΓΕΙΟΥ.pdf'
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-03  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Α' ΣΤΑΘΜΗΣ.pdf"

Quarantining: 100%|█████████▉| 525/527 [00:54<00:00,  9.74it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ3-04  - ΚΤΗΡΙΟ 3 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-01  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ ΘΕΜΕΛΙΩΣΗΣ Α' ΣΤΑΘΜΗΣ.pdf"

Quarantining: 100%|██████████| 527/527 [00:54<00:00,  9.60it/s]

FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: "Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf" -> "..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ4-02  - ΚΤΗΡΙΟ 4 ΞΥΛΟΤΥΠΟΣ Β', Γ' ΣΤΑΘΜΗΣ.pdf"
FAILED: Z:\SONADO-IK-801455240\10_PROJECTS\HTL0049-01_OITYLO-KOKKALA_MANI\04_DESIGN_ENGINEERING\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\PDF ΣΤΑΤΙΚΑ\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf -> [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\SONADO-IK-801455240\\10_PROJECTS\\HTL0049-01_OITYLO-KOKKALA_MANI\\04_DESIGN_ENGINEERING\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf' -> '..\\quarantine\\run_20260302_141826\\ΤΕΛΙΚΗ ΜΕΛΕΤΗ ΑΡΧΙΤΕΚΤΟΝΙΚΑ_ΣΤΑΤΙΚΑ\\ΣΤΑΤΙΚΗ ΜΕΛΕΤΗ\\PDF ΣΤΑΤΙΚΑ\\ΣΤ5-01  - ΒΙΟΛΟΓΙΚΟΣ ΚΑΘΑΡΙΣΜΟΣ & ΔΕΞΑΜΕΝΗ ΞΥΛΟΤΥΠΟΙ.pdf'
Moved 0/527 files to ..\quarantine\run_20260302_141826